# docker-compose.prod.yml
services:
  puppet:
    image: puppet
    container_name: puppet
    restart: always
    volumes:
      - ./files:/app/files
      - ./models:/app/models
    networks:
      - interservices

networks:
  interservices:
    external: true
