# docker-compose.yml
services:
  puppet:
    image: puppet
    container_name: puppet
    build: .
    ports:
      - "3004:8000"
    volumes:
      - .:/app
      - ./files:/app/files
      - ./models:/app/models