# docker-compose.prod.yml
services:
  vergo_puppet:
    image: vergo_puppet
    container_name: vergo_puppet
    ports:
      - "3004:8000"
    restart: always
    volumes:
      - ./files:/app/files
    extra_hosts:
      - 'host.docker.internal:host-gateway'
