# pytest.ini
[pytest]
pythonpath = .
python_files = *_test.py
filterwarnings =
    ignore:torch\.utils\._pytree\._register_pytree_node is deprecated:UserWarning

# Inject environment variables automatically
env =
    SECRET_KEY=mocked-secret-key
    MONGO_URI=mongodb://localhost:27017
    MODE=test