###
POST {{host}}/create_model
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_create.json

###
PATCH {{host}}/update_model
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_create.json


###
POST {{host}}/train_model
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "train_file": "o3_train_2502281000.json"
}

###
POST {{host}}/train_model
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_train.json

###
POST {{host}}/train_model_from_file
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "file_name": "o3_train_2502281000.json"
}

###
POST {{host}}/super_train_model
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "iterate": 10,
  "train_file": "o3_test_250223101541.json",
  "test_file": "o3_train_250223101541.json"
}


###
POST {{host}}/search
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "vector": ["man", "bicep", "curl"]
}

###
POST {{host}}/prepare_cache
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "search_vectors": [
    ["sit", "up"],
    ["push", "up"]
  ]
}

### 
POST {{host}}/test
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_test.json

### 
POST {{host}}/test
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "test_file": "o3_test_2502151700.json"
}