// doc\o5_embedding\o5_embedding.http

### Train the embedding model
POST {{host}}/embedding/create
Authorization: Bearer {{token}}

{
  "model_name": "puppet-o5",
  "vocab_path": "embedding_vocab.json",
  "trainset_path": "embedding_train.json"
}


### Train the embedding model
POST {{host}}/embedding/train
Authorization: Bearer {{token}}

{
  "model_name": "puppet-o5",
  "vocab_path": "embedding_vocab.json",
  "trainset_path": "embedding_train.json"
}

### Encode a sentence
POST {{host}}/embedding/encode
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "model_name": "puppet-o5",
  "sentence": "My red bicycle"
}

### Compute similarity
POST {{host}}/embedding/similarity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "model_name": "puppet-o5",
  "sentence1": "un vélo rouge",
  "sentence2": "un grand chapeau"
}
