###
POST {{host}}/create_model
Content-Type: application/json

{
  "name": "model1",
  "dictionary": [
    ["ab", "abdominal", "ashwa", "bhujang", "man", "old", "stretch"],
    ["ab", "abdominal", "cable", "man", "rotation"],
    ["ab", "abdominal", "foot", "lift", "man", "one", "prone", "single", "strength"],
    ["ab", "abdominal", "foot", "lift", "one", "prone", "single", "strength", "woman"],
    ["ab", "art", "ball", "bench", "gym", "man", "med", "practicing", "russian", "swiss", "twist"],
    ["ab", "athlete", "back", "breath", "holding", "lotus", "man", "paripurna", "self", "sitting", "stand", "sunken", "yoga"],
    ["ab", "athlete", "back", "breath", "holding", "lotus", "paripurna", "self", "sitting", "stand", "sunken", "woman", "yoga"],
    ["ab", "back", "dumbbell", "four", "loss", "sport", "stretch", "superman", "woman"],
    ["ab", "bend", "lat", "resistance", "strap", "woman"],
    ["ab", "body", "crucifix", "crunch", "man", "standing", "tutorial"],
    ["ab", "control", "lunge", "rear", "woman"],
    ["ab", "crunch", "layered", "reverse"],
    ["ab", "crunch", "machine", "man", "muscle", "press", "young"],
    ["ab", "crunch", "machine", "muscle", "press", "woman", "young"],
    ["ab", "crunch", "man", "reach", "toe"],
    ["ab", "deadlift", "kettlebell", "man"],
    ["ab", "down", "man", "movement", "plank", "push", "stepping", "up"],
    ["ab", "down", "puppy", "woman"],
    ["ab", "elbow", "forward", "hiit", "introduction", "knee", "man", "overhead", "plank", "stand", "tutorial"],
    ["ab", "elbow", "four", "ii", "introduction", "knee", "plank", "stand", "step", "tutorial", "woman"],
    ["ab", "incline", "layered", "plank", "shoulder", "tap", "woman"],
    ["ab", "knee", "lift", "resistance", "standing", "strap", "woman"],
    ["ab", "lat", "man", "skater", "standing"],
    ["ab", "layered", "plank", "shoulder", "tap"],
    ["ab", "layered", "plank", "shoulder", "tap"],
    ["ab", "resistance", "sitting", "strap", "twist", "woman"],
    ["abdominal", "ball", "bosu", "climber", "man", "mountain"],
    ["abdominal", "ball", "man", "plank", "swiss"],
    ["abdominal", "ball", "plank", "swiss", "woman"],
    ["abdominal", "body", "dumbbell", "foot", "lift", "man", "prone"],
    ["abdominal", "bug", "dead", "editable", "file", "layer", "man"],
    ["abdominal", "bug", "dead", "editable", "file", "layer", "woman"],
    ["abdominal", "cable", "crunch", "kneeling", "man"],
    ["abdominal", "circle", "editable", "file", "grip", "gymnastic", "layer", "man"],
    ["abdominal", "crunch", "folded", "man"],
    ["abdominal", "crunch", "man"],
    ["abdominal", "crunch", "man", "modified"],
    ["abdominal", "crunch", "man", "star"],
    ["abdominal", "crunch", "modified", "woman"],
    ["abdominal", "crunch", "modified", "woman"],
    ["abdominal", "dumbbell", "foot", "man", "stretch", "weighted"],
    ["abdominal", "editable", "file", "foot", "hanging", "knee", "layer", "lift", "man"],
    ["abdominal", "editable", "file", "foot", "hanging", "knee", "layer", "lift", "man"],
    ["abdominal", "excercise", "man", "twist"],
    ["abdominal", "foot", "hanging", "lat", "lift", "man"],
    ["abdominal", "foot", "knee", "man", "stretch", "up"],
    ["abdominal", "high", "kick", "man", "march", "martial", "stepping"],
    ["abdominal", "ii", "jathara", "parivartanasana", "spinal", "stand", "supine", "supta", "twist", "woman"],
    ["abdominal", "kettlebell", "man", "plank"],
    ["abdominal", "lat", "man", "plank"],
    ["abdominal", "man", "plank"],
    ["abdominal", "man", "plank"],
    ["abdominal", "man", "plank", "roll"],
    ["abdominal", "man", "sit", "up"],
    ["abduction", "foot", "resistance", "squat", "strap", "woman"],
    ["abduction", "hip", "isometric", "man", "resistance", "strap"],
    ["abduction", "hip", "lat", "lift", "machine", "man"],
    ["abduction", "hip", "lat", "prone", "woman"],
    ["abductor", "adductor", "foot", "hip", "ii", "lat", "lift", "man", "prone", "step"],
    ["abductor", "adductor", "foot", "hip", "ii", "lat", "lift", "prone", "step", "woman"],
    ["abductor", "ham", "machine", "man", "using"],
    ["accomplished", "man", "siddhasana", "yoga"],
    ["accomplished", "siddhasana", "woman", "yoga"],
    ["ach", "arm", "art", "back", "four", "neck", "shoulder", "stand", "stretching", "treatment", "woman"],
    ["activity", "chair", "head", "healthy", "left", "man", "neck", "office", "right", "rolling", "rotation", "sitting", "stretch", "turn"],
    ["adduction", "adductor", "foam", "ham", "inner", "skater", "stretch", "woman"],
    ["adho", "aerial", "eka", "handstand", "legged", "mukha", "one", "pada", "prep", "stand", "vrksasana", "woman", "yoga"],
    ["adho", "aerial", "handstand", "mukha", "prep", "stand", "vrksasana", "woman", "yoga"],
    ["adho", "aerial", "handstand", "mukha", "stand", "vrksasana", "woman", "yoga"],
    ["adho", "down", "eka", "facing", "mukha", "pada", "puppy", "split", "stand", "svanasana", "woman"],
    ["adho", "facing", "legged", "mukha", "pada", "puppy", "stacked", "stand", "svanasana", "tri", "variation", "woman"],
    ["adho", "plank", "puppy", "renegade", "row", "tap", "woman"],
    ["adult", "athlete", "excercise", "jog", "man", "marathon", "minimalistic", "muscular", "outdoor", "running"],
    ["adult", "athlete", "excercise", "jog", "marathon", "minimalistic", "muscular", "outdoor", "running", "woman"],
    ["advanced", "bar", "calisthenic", "forward", "lift", "man", "tuck"],
    ["advanced", "bridge", "foot", "single", "woman"],
    ["advanced", "bridge", "woman"],
    ["aerial", "angel", "ardha", "baddha", "jump", "konasana", "stand", "viparita", "woman"],
    ["aerial", "angel", "baddha", "jump", "konasana", "stand", "woman", "yoga"],
    ["aerial", "baddha", "dancer", "king", "natarajasana", "stand", "woman"],
    ["aerial", "circel", "circle", "hip", "stand", "woman", "yoga"],
    ["aerial", "five", "pointed", "stand", "star", "tadasana", "utthita", "viparita", "woman", "yoga"],
    ["against", "high", "knee", "man", "wall"],
    ["agnistambhasana", "forward", "lean", "leaning", "legged", "man", "sitting", "stretch", "wide"],
    ["air", "forward", "ii", "man", "squat", "step"],
    ["air", "squat"],
    ["alanasan", "ashta", "chandrasana", "high", "lunge", "quad", "stretch", "woman"],
    ["alternating", "ball", "character", "lat", "med", "setu", "slam"],
    ["alternating", "body", "explosive", "four", "hamstring", "jump", "lower", "lunge", "step", "woman"],
    ["alternating", "character", "curl", "different", "dumbbell", "layer", "man", "training"],
    ["alternating", "clap", "foot", "lift", "woman"],
    ["alternating", "dumbbell", "swing", "woman"],
    ["alternating", "foot", "lift", "plank", "row", "woman"],
    ["alternating", "forward", "lift", "lunge", "woman"],
    ["alternating", "four", "kickback", "man", "pack", "pigeon", "puppy", "reach", "six", "stand"],
    ["alternating", "jump", "lunge", "man"],
    ["alternating", "jump", "man", "split", "squat"],
    ["alternating", "jump", "split", "squat", "woman"],
    ["alternating", "kickback", "pigeon", "puppy", "reach", "woman"],
    ["anantasana", "laghu", "lat", "reclining", "sahaja", "stand", "variation", "woman"],
    ["angel", "arm", "astavakrasana", "asymmetrical", "eight", "practicing", "stand", "swing", "woman", "yoga"],
    ["angel", "art", "bodybuilding", "calf", "chair", "degree", "dumbbell", "floor", "foot", "heel", "keep", "lift", "pushing", "sitting", "stretch", "toe", "woman"],
    ["angel", "baddha", "bhujangasana", "foot", "jump", "konasana", "pada", "salamba", "sphinx", "stand", "wall", "woman"],
    ["angel", "baddha", "foot", "headstand", "jump", "konasana", "salamba", "sirsasana", "stand", "woman", "yoga"],
    ["angel", "baddha", "jump", "konasana", "man", "stand"],
    ["angel", "bear", "hug", "snow", "stretch", "woman"],
    ["angel", "devaduuta", "fallen", "panna", "stand", "woman", "yoga"],
    ["angel", "forward", "padottanasana", "parivrtta", "prasarita", "revolved", "twist", "wide", "woman"],
    ["anjaneyasana", "crescent", "hand", "low", "lunge", "stand", "toe", "variation", "woman"],
    ["anjaneyasana", "low", "lunge", "man", "stand", "style", "trendy", "yoga"],
    ["anjaneyasana", "low", "lunge", "quad", "stand", "stretch", "woman"],
    ["ankle", "back", "during", "foot", "good", "ii", "pregnancy", "pumping", "relieve", "safe", "stand", "step", "swelling", "woman"],
    ["ankle", "calf", "stand", "stretching", "woman"],
    ["ankle", "circle", "man", "roll", "rotation"],
    ["ankle", "circle", "roll", "rotation", "woman"],
    ["ankle", "circle", "woman"],
    ["ankle", "dorsiflexion", "man", "resistance", "strap", "stretch"],
    ["ankle", "dorsiflexion", "resistance", "strap", "stretch", "woman"],
    ["ankle", "hop", "woman"],
    ["ankle", "jack", "jump", "woman"],
    ["ankle", "push", "tap", "up", "woman"],
    ["ankle", "squat", "stand", "stretch", "toe", "woman"],
    ["apanasana", "chest", "knee", "man", "stand"],
    ["archer", "calisthenic", "man", "stretch", "up"],
    ["ardha", "art", "chair", "man", "matsyendrasana", "office", "sitting", "spinal", "twist"],
    ["ardha", "art", "folded", "hand", "handstand", "kapinjalasana", "knee", "lat", "plank", "toe", "variation", "vasisthasana", "wall", "woman"],
    ["ardha", "athlete", "chair", "four", "man", "partial", "squat"],
    ["ardha", "athlete", "chair", "four", "partial", "squat", "woman"],
    ["ardha", "baddha", "boat", "jump", "lotus", "navasana", "padma", "stand", "woman", "yoga"],
    ["ardha", "baddha", "jump", "lat", "parivrtta", "plank", "revolved", "stand", "variation", "vasisthasana", "woman", "yoga"],
    ["ardha", "beautiful", "elbow", "fish", "girl", "laghu", "lotus", "matsyasana", "padmasana", "stand", "variation", "woman"],
    ["ardha", "bicep", "curl", "dumbbell", "static", "woman"],
    ["ardha", "bridge", "woman"],
    ["ardha", "camel", "raised", "stand", "toe", "ustrasana", "variation", "woman", "yoga"],
    ["ardha", "catur", "eka", "foot", "headstand", "janu", "kurpara", "one", "pada", "prep", "raised", "sirsasana", "svanasana", "tripod", "urdhva", "woman"],
    ["ardha", "chair", "matsyendrasana", "spinal", "twist", "woman"],
    ["ardha", "character", "foot", "four", "ii", "overhead", "pada", "purvottanasana", "reverse", "stand", "table", "utkatasana", "woman"],
    ["ardha", "character", "foot", "four", "overhead", "pada", "purvottanasana", "reverse", "stand", "table", "utkatasana", "woman"],
    ["ardha", "character", "foot", "four", "overhead", "pada", "purvottanasana", "reverse", "stand", "table", "utkatasana", "woman"],
    ["ardha", "character", "foot", "four", "overhead", "pada", "purvottanasana", "reverse", "stand", "table", "utkatasana", "woman"],
    ["ardha", "fish", "lord", "matsyendrasana", "woman"],
    ["ardha", "foot", "modified", "one", "push", "up", "woman"],
    ["ardha", "hanumanasana", "monkey", "split", "stand", "woman"],
    ["ardha", "jump", "kasyapasana", "lat", "lotus", "plank", "woman"],
    ["arm", "ball", "character", "med", "push", "setu", "single", "up", "woman"],
    ["arm", "banded", "folded", "man", "row", "single", "up"],
    ["arm", "battle", "folded", "man", "rope", "slam"],
    ["arm", "bicep", "cable", "curl", "hammer", "man"],
    ["arm", "bicep", "cable", "curl", "hammer", "man", "woman"],
    ["arm", "bicep", "curl", "man", "resistance", "strap"],
    ["arm", "big", "circle", "ii", "woman"],
    ["arm", "big", "circle", "woman"],
    ["arm", "body", "crucifix", "man", "shoulder", "standing", "stretch"],
    ["arm", "body", "crucifix", "man", "shoulder", "standing", "stretch"],
    ["arm", "body", "crucifix", "shoulder", "standing", "stretch", "woman"],
    ["arm", "bodyweight", "squat", "up", "woman"],
    ["arm", "bottle", "forward", "lift", "man", "one", "single", "water"],
    ["arm", "bottle", "forward", "lift", "one", "single", "water", "woman"],
    ["arm", "bridge", "character", "floor", "glute", "man", "press", "setu", "single"],
    ["arm", "bridge", "character", "floor", "glute", "press", "setu", "single", "woman"],
    ["arm", "bridge", "foot", "glute", "man", "single"],
    ["arm", "carry", "dumbbell", "farmer", "man", "one", "single", "stepping", "suitcase"],
    ["arm", "character", "dumbbell", "overhead", "press", "setu", "shoulder", "single", "woman"],
    ["arm", "character", "folded", "man", "row", "setu", "single", "up"],
    ["arm", "character", "folded", "man", "row", "setu", "single", "up"],
    ["arm", "character", "folded", "row", "setu", "single", "up", "woman"],
    ["arm", "chest", "man", "one", "standing", "stretch", "wall"],
    ["arm", "circle", "man"],
    ["arm", "circle", "man", "standing"],
    ["arm", "circle", "woman"],
    ["arm", "crucifix", "lat", "lunge", "woman"],
    ["arm", "crunch", "editable", "file", "layer", "long", "man"],
    ["arm", "down", "forearm", "lat", "plank", "stand", "vasisthasana", "woman"],
    ["arm", "dumbbell", "elbow", "man", "rotation", "scarecrow", "shoulder"],
    ["arm", "dumbbell", "elbow", "rotation", "scarecrow", "shoulder", "woman"],
    ["arm", "dumbbell", "extension", "overhead", "single", "sitting", "tricep", "woman"],
    ["arm", "dumbbell", "forward", "lift", "man", "shoulder", "two"],
    ["arm", "dumbbell", "forward", "lift", "shoulder", "two", "woman"],
    ["arm", "dumbbell", "handed", "lat", "leaning", "lift", "man", "one", "single"],
    ["arm", "dumbbell", "high", "man", "plate", "push", "single", "up"],
    ["arm", "dumbbell", "man", "one", "snatch"],
    ["arm", "eka", "flying", "hurdler", "ii", "koundinyasana", "legged", "one", "pada", "split", "stand", "swing", "twisted", "woman"],
    ["arm", "extension", "folded", "lat", "lift", "man", "overhead"],
    ["arm", "folded", "kickback", "tricep", "up", "woman"],
    ["arm", "folded", "lat", "laterally", "lift", "man", "until"],
    ["arm", "foot", "long", "man", "pistol", "single", "squat"],
    ["arm", "foot", "long", "pistol", "single", "squat", "trx", "woman"],
    ["arm", "hand", "hasta", "raised", "stand", "uttanasana", "woman"],
    ["arm", "hand", "man", "neck", "shoulder", "stretching"],
    ["arm", "kettlebell", "man", "one", "press", "shoulder"],
    ["arm", "kettlebell", "man", "one", "row"],
    ["arm", "kettlebell", "man", "swing", "two"],
    ["arm", "kettlebell", "one", "row", "woman"],
    ["arm", "kettlebell", "swing", "two", "woman"],
    ["arm", "kickback", "one", "tricep", "woman"],
    ["arm", "lat", "man", "pulldown", "straight"],
    ["arm", "lat", "overhead", "plank", "twist", "vasisthasana", "woman"],
    ["arm", "lat", "pulldown", "rope", "straight", "woman"],
    ["arm", "man", "pulldown", "straight"],
    ["arm", "swing", "woman"],
    ["arnold", "bench", "man", "press", "sitting"],
    ["arnold", "bench", "press", "sitting", "woman"],
    ["arnold", "man", "press"],
    ["arnold", "press", "woman"],
    ["art", "athlete", "bag", "boxer", "boxing", "gym", "low", "martial", "punch", "punching", "training", "woman"],
    ["art", "floor", "foot", "four", "man", "sit", "stretch"],
    ["art", "hanumanasana", "split", "stand", "standing", "variation", "wall", "woman", "yoga"],
    ["ashtanga", "chest", "chin", "knee", "namaskar", "stand", "woman"],
    ["ashtangasana", "baddha", "eight", "hand", "hasta", "jump", "legged", "stand", "woman", "yoga"],
    ["ashtangasana", "eight", "legged", "stand", "woman", "yoga"],
    ["ashwa", "equestrian", "man", "sanchalanasana"],
    ["assistance", "chin", "resistance", "strap", "up", "woman"],
    ["assisted", "calf", "lift", "machine", "man", "standing"],
    ["assisted", "dip", "machine", "man", "sitting", "tricep"],
    ["assisted", "machine", "stretch", "up", "woman"],
    ["asymmetrical", "push", "up", "woman"],
    ["athlete", "character", "dumbbell", "folded", "gym", "minimalistic", "perform", "row", "setu", "style", "up"],
    ["baby", "happy", "stand", "woman"],
    ["back", "balance", "ball", "extension", "man", "swiss"],
    ["back", "behind", "curl", "man", "standing", "wrist"],
    ["back", "bhujang", "extension", "lift", "woman"],
    ["back", "cable", "exerciseflat", "forward", "man", "rope", "shoulder", "standing", "stretch"],
    ["back", "cable", "low", "man", "row", "sitting"],
    ["back", "cable", "low", "man", "row", "sitting"],
    ["back", "calisthenic", "lift", "man", "stand"],
    ["back", "chest", "knee", "lower", "stretch", "woman"],
    ["back", "crucifix", "lunge", "man"],
    ["back", "developer", "extension", "glute", "ham", "lift", "man"],
    ["back", "dumbbell", "man", "neck", "squat"],
    ["back", "dumbbell", "man", "shrug"],
    ["back", "extension", "prone", "woman"],
    ["back", "flye", "long", "overhead", "resistance", "reverse", "strap", "woman"],
    ["back", "foam", "overhead", "skater", "stretch", "woman"],
    ["back", "folded", "forward", "hand", "high", "lunge", "man", "twist"],
    ["back", "foot", "holding", "lizard", "pristhasana", "stand", "utthan", "variation", "woman"],
    ["back", "forward", "jump", "shuffle", "woman"],
    ["back", "grappling", "reach", "woman"],
    ["back", "jump", "woman", "yoga"],
    ["back", "kick", "lunge", "woman"],
    ["back", "man", "reach", "rotation", "standing", "stretch", "up"],
    ["backbend", "baddhanguliyasana", "hand", "interlocked", "long", "mountain", "stand", "tadasana", "utthita", "woman"],
    ["backgroun", "battle", "rope", "snake", "woman"],
    ["backside", "bag", "four", "good", "morning", "sandbag", "strength", "woman"],
    ["backward", "glute", "lift", "long", "resistance", "strap", "woman"],
    ["baddha", "eka", "foot", "intense", "jump", "niralamba", "one", "pada", "stand", "stretch", "uttanasana", "woman"],
    ["baddha", "jump", "lotus", "man", "padmasana"],
    ["baddha", "jump", "lotus", "padmasana", "stand", "supta", "woman", "yoga"],
    ["baddha", "jump", "lotus", "padmasana", "stand", "woman"],
    ["baddha", "jump", "lotus", "padmasana", "stand", "woman", "yoga"],
    ["bakasana", "crane", "crow", "kakasana", "lat", "parsva", "stand", "woman"],
    ["bakasana", "crow", "eagle", "foot", "garudasana", "pada", "stand", "woman"],
    ["bakasana", "crow", "man", "stand"],
    ["balance", "ball", "bridge", "curl", "foot", "hamstring", "hip", "lift", "man", "swiss"],
    ["balance", "ball", "bridge", "curl", "foot", "hamstring", "hip", "lift", "swiss", "woman"],
    ["balance", "ball", "crunch", "man", "swiss"],
    ["balance", "ball", "crunch", "swiss", "woman"],
    ["balance", "ball", "man", "push", "swiss", "up"],
    ["balance", "ball", "man", "rollout", "swiss"],
    ["balance", "ball", "man", "squat", "swiss", "wall"],
    ["balance", "ball", "push", "swiss", "up", "woman"],
    ["balance", "ball", "rollout", "swiss", "woman"],
    ["balancing", "bear", "column", "merudandasana", "sitting", "spinal", "stand", "straddle", "upward", "woman"],
    ["balancing", "bitilasana", "cow", "stand", "woman", "yoga"],
    ["balasana", "mukha", "needle", "parsva", "pasasana", "stand", "thread", "urdhva", "woman", "yoga"],
    ["ball", "bicep", "curl", "dumbbell", "man", "swiss"],
    ["ball", "body", "dumbbell", "foot", "lift", "man", "swiss"],
    ["ball", "body", "dumbbell", "foot", "lift", "swiss", "woman"],
    ["ball", "bosu", "bridge", "extension", "foot", "lift", "single", "thrust", "woman"],
    ["ball", "bosu", "bridge", "glute", "hip", "lift", "man"],
    ["ball", "bosu", "bridge", "glute", "hip", "lift", "woman"],
    ["ball", "bosu", "bridge", "glute", "hip", "lift", "woman"],
    ["ball", "bosu", "down", "man", "plank", "push", "stepping", "up"],
    ["ball", "bosu", "down", "plank", "push", "stepping", "up", "woman"],
    ["ball", "bosu", "foot", "knee", "stretch", "tuck", "woman"],
    ["ball", "bosu", "foot", "lift", "plank", "woman"],
    ["ball", "bosu", "man", "static", "swing"],
    ["ball", "bosu", "squat", "woman"],
    ["ball", "bosu", "static", "swing", "woman"],
    ["ball", "character", "chop", "med", "setu", "woman", "wood"],
    ["ball", "character", "chop", "med", "setu", "woman", "wood"],
    ["ball", "character", "lat", "med", "setu", "slam", "throw"],
    ["ball", "character", "med", "pass", "rotational", "setu"],
    ["ball", "character", "med", "setu", "swing", "woman"],
    ["ball", "character", "med", "setu", "up"],
    ["ball", "character", "med", "setu", "up", "woman"],
    ["ball", "chest", "floor", "laying", "med", "pass", "press"],
    ["ball", "chest", "floor", "laying", "med", "pass", "press", "woman"],
    ["ball", "chest", "med", "push", "up"],
    ["ball", "chest", "med", "step", "woman"],
    ["ball", "deadlift", "med", "woman"],
    ["ball", "lunge", "med", "overhead", "press", "reverse", "woman"],
    ["ball", "man", "med", "reach", "squat"],
    ["ball", "man", "squeeze", "swiss"],
    ["ball", "massage", "neck", "woman"],
    ["ball", "med", "rotation", "sit", "wall", "woman"],
    ["ball", "med", "squat", "woman"],
    ["ball", "rolling", "woman"],
    ["banana", "bananasana", "man", "stand"],
    ["banana", "bananasana", "stand", "woman"],
    ["banded", "flye", "lat", "man", "reverse"],
    ["banded", "walk", "woman"],
    ["bandha", "bridge", "chakrasana", "physical", "setu", "shoulderstand", "stand", "woman", "yoga"],
    ["bandha", "bridge", "man", "setu", "shoulderstand", "stand"],
    ["bandha", "bridge", "man", "setu", "shoulderstand", "stand", "wall"],
    ["bar", "bench", "bridge", "glute", "man"],
    ["bar", "bicep", "bodybuilding", "character", "curl", "dumbbell", "ez", "gym", "layer", "making", "man", "preacher"],
    ["bar", "body", "folded", "man", "overhead", "row", "up"],
    ["bar", "cable", "character", "curl", "different", "layer", "low", "man", "pulley", "straight"],
    ["bar", "cage", "deadlift", "hex", "squat", "trap", "woman"],
    ["bar", "calisthenic", "forward", "lift", "man"],
    ["bar", "calisthenic", "forward", "lift", "woman"],
    ["bar", "calisthenic", "four", "man", "movement", "muscle", "step", "up"],
    ["bar", "dip", "gym", "man", "parallel"],
    ["bar", "extension", "ez", "hand", "man", "overhead", "tricep"],
    ["bar", "floor", "man", "push", "up"],
    ["bar", "jefferson", "man", "squat"],
    ["bar", "man", "perfect", "plank", "push", "straddle", "up"],
    ["bar", "perfect", "plank", "push", "straddle", "up", "woman"],
    ["basketball", "shot", "woman"],
    ["battle", "folded", "rope", "wave", "woman"],
    ["battle", "jack", "jump", "rope", "woman"],
    ["bear", "crawl", "healthy", "introduction", "man", "step"],
    ["bear", "walk", "woman"],
    ["beautiful", "girl", "lat", "plank", "sage", "stand", "vasistha", "vasisthasana", "woman"],
    ["beautiful", "girl", "marichi", "marichyasana", "sage", "stand", "variation", "woman"],
    ["beautiful", "girl", "stand", "twisted", "vakrasana", "woman"],
    ["behind", "eka", "foot", "head", "pada", "sirsasana", "stand", "woman", "yoga"],
    ["bell", "character", "folded", "kettlebell", "man", "rowing", "setu", "smash", "up"],
    ["bell", "character", "goblet", "kettle", "man", "setu", "squat"],
    ["bellow", "bhastrika", "breath", "man", "pranayama", "yoga"],
    ["bellow", "bhastrika", "breath", "pranayama", "woman", "yoga"],
    ["bench", "boxing", "hop", "jump", "man", "sport", "up"],
    ["bench", "butterfly", "kick", "long", "sitting", "woman"],
    ["bench", "cable", "chest", "day", "flye", "man"],
    ["bench", "chair", "dip", "man", "tricep"],
    ["bench", "character", "crunch", "reverse", "setu"],
    ["bench", "character", "dumbbell", "incline", "man", "row"],
    ["bench", "chest", "dumbbell", "man", "press"],
    ["bench", "chest", "dumbbell", "man", "press"],
    ["bench", "close", "hand", "man", "press"],
    ["bench", "crunch", "decline", "man"],
    ["bench", "crunch", "incline", "man", "reverse"],
    ["bench", "crusher", "dumbbell", "head", "man"],
    ["bench", "curl", "dumbbell", "forearm", "man", "reverse", "wrist"],
    ["bench", "dip", "man", "tricep"],
    ["bench", "dip", "man", "tricep"],
    ["bench", "dip", "tricep", "woman"],
    ["bench", "dumbbell", "flye", "man", "overhead"],
    ["bench", "dumbbell", "hand", "incline", "man", "press", "reverse"],
    ["bench", "dumbbell", "incline", "man", "press", "twist"],
    ["bench", "dumbbell", "man", "step", "up"],
    ["bench", "foot", "knee", "sitting", "stretch", "up", "woman"],
    ["bench", "man", "pike", "push", "up"],
    ["bend", "character", "dumbbell", "lat", "setu", "standing", "woman"],
    ["bend", "hand", "hip", "lat", "man", "sport", "stretching"],
    ["bend", "knee", "man", "prone", "resistance", "strap"],
    ["bend", "knee", "prone", "resistance", "strap", "woman"],
    ["bend", "knee", "prone", "woman"],
    ["bharmanasana", "overhead", "stand", "table", "woman", "yoga"],
    ["bheka", "bhujang", "bhujangasana", "frog", "stand", "woman", "yoga"],
    ["bherundasana", "chin", "ganda", "stand", "woman", "yoga"],
    ["bhujang", "bhujangasana", "rising", "stand", "standing", "stiti", "utthita", "woman", "yoga"],
    ["bhujang", "lat", "pulldown", "woman"],
    ["bicep", "cable", "character", "curl", "different", "layer", "man", "standing"],
    ["bicep", "character", "curl", "different", "dumbbell", "hammer", "layer", "man"],
    ["bicep", "character", "curl", "different", "dumbbell", "hammer", "layer", "man", "standing", "training"],
    ["bicep", "character", "curl", "different", "dumbbell", "hammer", "layer", "man", "training"],
    ["bicep", "character", "curl", "different", "dumbbell", "hammer", "layer", "woman"],
    ["bicep", "character", "curl", "different", "dumbbell", "hammer", "layer", "woman"],
    ["bicep", "character", "curl", "different", "dumbbell", "layer", "man", "standing", "training"],
    ["bicep", "character", "curl", "different", "dumbbell", "layer", "woman"],
    ["bicep", "character", "curl", "different", "hammer", "layer", "man", "rope"],
    ["bicep", "curl", "dumbbell", "hammer", "man", "preacher", "sitting"],
    ["bicep", "curl", "dumbbell", "man", "sitting"],
    ["bicep", "curl", "dumbbell", "man", "standing"],
    ["bicep", "curl", "lunge", "stationary", "woman"],
    ["bicep", "curl", "woman"],
    ["bicep", "lat", "long", "resistance", "strap", "stretch", "woman"],
    ["bicep", "stretch", "woman"],
    ["big", "dandasana", "hand", "ii", "padangustha", "staff", "stand", "toe", "woman"],
    ["block", "boxing", "clean", "dumbbell", "man"],
    ["block", "during", "lolasana", "stand", "woman", "yoga"],
    ["boat", "foot", "hand", "navasana", "parivrtta", "stand", "twist", "variation", "woman"],
    ["boat", "high", "navasana", "stand", "utthita", "woman", "yoga"],
    ["boat", "navasana", "paripurna", "stand", "woman"],
    ["body", "climber", "crucifix", "mountain", "woman"],
    ["body", "dumbbell", "lunge", "stepping", "woman"],
    ["body", "dumbbell", "man", "overhead", "press", "shoulder"],
    ["body", "dumbbell", "man", "overhead", "press", "shoulder", "sitting"],
    ["body", "dumbbell", "man", "overhead", "press", "shoulder", "training"],
    ["body", "entire", "four", "ii", "jump", "lat", "lower", "squat", "step", "strengthen", "woman"],
    ["bodybuilding", "chin", "dynamic", "gym", "healthy", "lifestyle", "man", "up"],
    ["bodyweight", "bridge", "butt", "curling", "hip", "lift", "man", "reach", "shoulder"],
    ["bodyweight", "calf", "external", "lift", "man", "rotation"],
    ["bodyweight", "calf", "external", "lift", "rotation", "woman"],
    ["bodyweight", "man", "martial", "overhead", "press", "shoulder"],
    ["bodyweight", "man", "squat"],
    ["bodyweight", "squat", "woman"],
    ["bodyweight", "squat", "woman"],
    ["bodyweight", "squat", "woman"],
    ["bottle", "lunge", "man", "reverse", "stand", "water"],
    ["bottle", "lunge", "reverse", "stand", "water", "woman"],
    ["bow", "chakrasana", "dhanurasana", "roller", "stand", "upward", "urdhva", "woman"],
    ["bow", "dhanura", "eka", "foot", "legged", "one", "pada", "phalakasana", "plank", "stand", "woman"],
    ["boxer", "punch", "squat", "woman"],
    ["boxing", "breath", "stretch", "woman"],
    ["boxing", "dumbbell", "plyo", "step", "up"],
    ["boxing", "grip", "man", "pike", "push", "up"],
    ["boxing", "high", "jump", "woman"],
    ["boy", "foot", "hamstring", "hand", "heron", "holding", "intense", "krounchasana", "man", "stand", "stretch", "up", "yogi"],
    ["breakdancer", "kick", "woman"],
    ["bridge", "chest", "flye", "glute", "woman"],
    ["bridge", "dumbbell", "flute", "high", "hip", "lift", "woman"],
    ["bridge", "dumbbell", "glute"],
    ["bridge", "dumbbell", "glute", "high", "hip", "lift", "man"],
    ["bridge", "foot", "glute", "single", "woman"],
    ["bridge", "foot", "single", "woman"],
    ["bridge", "frog", "woman"],
    ["bridge", "glute"],
    ["bridge", "twist", "woman"],
    ["bridge", "wall", "woman"],
    ["broomstick", "pole", "shoulder", "stretch", "woman"],
    ["bulgarian", "man", "split", "squat"],
    ["bulgarian", "split", "squat", "woman"],
    ["bulgarian", "split", "squat", "woman"],
    ["bum", "explosive", "kick", "woman"],
    ["bunny", "handstand", "hop", "pike", "prep", "stand", "woman", "yoga"],
    ["burpee"],
    ["burpee", "chest", "floor", "man"],
    ["burpee", "diagram", "push", "squat", "stand", "step", "tutorial", "woman"],
    ["burpee", "man", "push", "squat", "stand", "step"],
    ["burpee", "push", "up", "woman"],
    ["burpee", "woman"],
    ["butt", "character", "kick", "man", "setu"],
    ["butt", "kick"],
    ["butterfly", "deck", "flye", "machine", "man", "pec", "sitting"],
    ["butterfly", "kick", "squat", "woman"],
    ["butterfly", "kick", "woman"],
    ["butterfly", "stretch", "woman"],
    ["buttock", "firming", "foot", "four", "healthy", "ii", "illustrated", "lunge", "man", "step", "tutorial"],
    ["buttock", "firming", "foot", "four", "healthy", "ii", "illustrated", "lunge", "step", "tutorial", "woman"],
    ["buttock", "four", "hip", "lunge", "step", "up", "woman"],
    ["buttock", "four", "hip", "squat", "sumo", "wide", "woman"],
    ["cable", "character", "crossover", "flye", "man", "press", "standing"],
    ["cable", "character", "crucifix", "curl", "different", "layer", "man", "overhead"],
    ["cable", "character", "crucifix", "curl", "different", "layer", "overhead", "woman"],
    ["cable", "chest", "crossover", "flye", "low", "man", "pulley", "upward"],
    ["cable", "chest", "man", "push"],
    ["cable", "equipment", "external", "four", "gym", "ii", "knee", "maintain", "rotation", "shoulder", "stable", "stand", "step", "strong", "woman"],
    ["cable", "extension", "folded", "man", "tricep", "up"],
    ["cable", "extension", "hip", "man"],
    ["cable", "extension", "kickback", "low", "man", "pulley", "tricep"],
    ["cable", "forward", "man", "shoulder", "stretch"],
    ["cable", "kickback", "tricep", "woman"],
    ["cable", "man", "pushdown", "rope"],
    ["cable", "man", "row", "squat"],
    ["cable", "man", "stretch"],
    ["cable", "row", "squat", "woman"],
    ["cable", "row", "standing", "woman"],
    ["cable", "stretch", "woman"],
    ["calf", "character", "dumbbell", "lift", "man", "setu", "standing"],
    ["calf", "character", "foot", "man", "setu", "straight", "stretch"],
    ["calf", "character", "jump", "lift", "man", "press", "setu"],
    ["calf", "dumbbell", "lift", "man", "standing"],
    ["calf", "dumbbell", "lift", "standing", "woman"],
    ["calf", "equipment", "gym", "lift", "machine", "man", "sitting", "using"],
    ["calf", "foam", "skater", "stretch", "woman"],
    ["calf", "jump", "lift", "press", "woman"],
    ["calf", "lift", "plie", "squat", "woman"],
    ["calf", "lift", "squat", "wide", "woman"],
    ["calf", "man", "resistance", "strap", "stretch"],
    ["calisthenic", "chin", "man", "up", "weighted"],
    ["calisthenic", "finger", "man", "plank"],
    ["calisthenic", "man", "parallette", "plank", "tuck"],
    ["cardio", "concept", "design", "four", "stepping", "training", "woman"],
    ["cardio", "jump", "man", "rope"],
    ["cardio", "jump", "man", "tuck"],
    ["cardio", "jump", "rope", "woman"],
    ["cardio", "jump", "rope", "woman"],
    ["cartoon", "character", "demonstrating", "during", "gymnastic", "hatha", "ii", "man", "practicing", "soldier", "stand", "training", "virabhadrasana", "yoga"],
    ["cat", "cow", "man", "stand", "stretch", "yoga"],
    ["cat", "cow", "stretch", "woman", "yoga"],
    ["cat", "man", "pulling", "stand", "tail"],
    ["cat", "pulling", "stand", "tail", "woman"],
    ["catur", "eka", "elbow", "headstand", "janu", "knee", "kurpara", "one", "prep", "sirsasana", "svanasana", "tripod", "woman"],
    ["chair", "curl", "hamstring", "man", "salamba", "standing"],
    ["chair", "man", "stand"],
    ["chair", "salamba", "shoulderstand", "stand", "woman", "yoga"],
    ["chakrasana", "flow", "roller", "stand", "woman", "yoga"],
    ["character", "chest", "hammer", "machine", "man", "press", "sitting", "strength"],
    ["character", "chin", "setu", "up", "woman"],
    ["character", "clap", "dynamic", "man", "push", "up", "variation"],
    ["character", "climber", "kettlebell", "man", "mountain", "setu"],
    ["character", "concentration", "curl", "different", "dumbbell", "layer", "man"],
    ["character", "crunch", "man", "resistance", "setu", "weighted"],
    ["character", "crunch", "resistance", "setu", "weighted", "woman"],
    ["character", "deadlift", "handed", "kettlebell", "man", "one", "setu"],
    ["character", "deadlift", "handed", "kettlebell", "man", "one", "setu"],
    ["character", "deadlift", "kettlebell", "setu", "woman"],
    ["character", "dip", "gironda", "man", "setu"],
    ["character", "dip", "man", "master", "setu", "tricep"],
    ["character", "dumbbell", "foot", "man", "pistol", "setu", "single", "squat"],
    ["character", "foot", "kettlebell", "man", "setu", "smashbell", "squat", "training"],
    ["character", "foot", "man", "pistol", "setu", "single", "squat"],
    ["character", "forward", "lift", "plate", "setu", "shoulder", "standing", "woman"],
    ["character", "four", "man", "stretch"],
    ["character", "goblet", "kettlebell", "setu", "squat", "woman"],
    ["character", "hand", "kettlebell", "man", "one", "push", "setu", "up"],
    ["character", "kettlebell", "kneeling", "man", "press"],
    ["character", "kettlebell", "lunge", "man", "rotation", "setu", "upperbody"],
    ["character", "kettlebell", "lunge", "press", "setu", "woman"],
    ["character", "kettlebell", "man", "setu", "windmill"],
    ["character", "kettlebell", "russian", "setu", "twist", "woman"],
    ["character", "kick", "plank", "reverse", "setu"],
    ["character", "knee", "layered", "plank"],
    ["character", "knee", "man", "modified", "push", "up"],
    ["character", "knee", "modified", "push", "up", "woman"],
    ["character", "mason", "russian", "setu", "sit", "twist"],
    ["character", "mason", "russian", "setu", "twist", "weighted", "woman"],
    ["character", "pada", "skater", "stand", "trikonasana", "vakra", "woman", "yoga"],
    ["character", "squat", "woman"],
    ["chaturanga", "dandasana", "low", "plank", "stand", "woman"],
    ["chest", "crossover", "long", "resistance", "strap", "woman"],
    ["chest", "crucifix", "curl", "standing", "woman"],
    ["chest", "diamond", "four", "man", "push", "tricep", "up"],
    ["chest", "diamond", "four", "man", "push", "tricep", "up"],
    ["chest", "dumbbell", "flye", "folded", "man", "reverse", "salamba", "up"],
    ["chest", "dumbbell", "flye", "folded", "reverse", "salamba", "up", "woman"],
    ["chest", "dumbbell", "press", "woman"],
    ["chest", "extension", "man", "overhead", "prone"],
    ["chest", "flye", "woman"],
    ["chest", "knee", "spinal", "stretch", "twist", "woman"],
    ["chest", "man", "opener", "resistance", "strap", "stretch"],
    ["chest", "opener", "resistance", "strap", "stretch", "woman"],
    ["chest", "press", "resistance", "strap"],
    ["chest", "stretch", "woman"],
    ["child", "man", "stand", "stretch"],
    ["child", "stand"],
    ["child", "stand", "stretch", "woman"],
    ["chop", "crunch", "woman"],
    ["chop", "dumbbell", "man", "wood"],
    ["chop", "swing", "woman"],
    ["circle", "grip", "gymnastic", "woman"],
    ["circle", "hip", "woman"],
    ["circle", "knee", "woman"],
    ["circle", "sky", "woman"],
    ["clean", "dumbbell", "jerk", "man", "overhead", "paripurna", "press"],
    ["climber", "man", "mountain"],
    ["climber", "mountain"],
    ["climber", "mountain", "standing", "woman"],
    ["climber", "mountain", "twist", "woman"],
    ["climber", "mountain", "woman"],
    ["close", "hand", "lat", "man", "pulldown"],
    ["cock", "kukkutasana", "rooster", "stand", "woman"],
    ["compass", "stand", "sundial", "surya", "woman", "yantrasana", "yoga"],
    ["concentration", "curl", "dumbbell", "sitting", "woman"],
    ["concentration", "curl", "woman"],
    ["cool", "down", "flexibility", "improvement", "man", "quadricep", "stand", "stretch", "swing"],
    ["cossack", "man", "squat"],
    ["cossack", "squat", "woman"],
    ["cow", "forward", "gomukhasana", "man", "stand"],
    ["crab", "kick", "woman"],
    ["crab", "man", "toe", "touch"],
    ["crab", "resistance", "stepping", "strap", "woman"],
    ["crossover", "step", "up", "woman"],
    ["crucifix", "dumbbell", "lunge", "woman"],
    ["crucifix", "jack", "woman"],
    ["crunch", "foot", "lat", "lift", "woman"],
    ["crunch", "incline", "man", "punch"],
    ["crunch", "lat", "plank", "woman"],
    ["crunch", "man", "oblique"],
    ["crunch", "man", "sprinter"],
    ["crunch", "oblique", "woman"],
    ["crunch", "sprinter", "woman"],
    ["curl", "dumbbell", "hammer", "man", "sitting"],
    ["curl", "dumbbell", "hammer", "man", "standing"],
    ["curl", "foot", "hamstring", "woman"],
    ["curl", "foot", "man", "prone"],
    ["curl", "foot", "prone", "woman"],
    ["curl", "foot", "prone", "woman"],
    ["curl", "foot", "sitting", "woman"],
    ["curl", "hammer", "hand", "long", "resistance", "strap", "woman"],
    ["curl", "lat", "lunge", "woman"],
    ["curl", "press", "sit", "woman"],
    ["curl", "split", "squat", "woman"],
    ["curling", "degree", "jump", "sport", "squat", "training", "woman"],
    ["curling", "lat", "man", "mountain", "parsva", "stand", "tadasana"],
    ["curtsy", "kick", "lat", "lift", "lunge", "woman"],
    ["curtsy", "lat", "lunge", "woman"],
    ["db", "deadlift", "foot", "single", "woman"],
    ["deadlift", "dumbbell", "four", "glute", "romanian", "stand", "woman"],
    ["deadlift", "dumbbell", "man"],
    ["deadlift", "dumbbell", "man"],
    ["deadlift", "dumbbell", "man", "romanian"],
    ["deadlift", "dumbbell", "man", "sumo"],
    ["deadlift", "dumbbell", "sumo", "woman"],
    ["deadlift", "dumbbell", "woman"],
    ["deadlift", "dumbbell", "woman"],
    ["deadlift", "foot", "resistance", "single", "strap", "woman"],
    ["deadlift", "kettlebell", "legged", "man", "one"],
    ["deadlift", "kettlebell", "legged", "one", "woman"],
    ["deadlift", "man", "resistance", "strap"],
    ["decline", "push", "up", "woman"],
    ["decline", "push", "up", "woman"],
    ["degree", "lunge", "man", "rolling", "rotation"],
    ["delt", "dumbbell", "flye", "folded", "lat", "lift", "rear", "up", "woman"],
    ["delt", "dumbbell", "flye", "folded", "lat", "lift", "rear", "up", "woman"],
    ["delt", "flye", "machine", "man", "rear"],
    ["delt", "flye", "machine", "rear", "woman"],
    ["delt", "folded", "lift", "man", "rear", "sitting", "up"],
    ["delt", "forward", "rear", "sitting", "stretch", "woman"],
    ["diamond", "push", "pyramid", "up", "woman"],
    ["diamond", "push", "up"],
    ["dip"],
    ["dip", "floor", "man", "tricep"],
    ["dip", "hip", "plank", "woman"],
    ["dip", "man", "trice"],
    ["dip", "trice", "woman"],
    ["dipping", "man", "pigeon"],
    ["doe", "fitball", "floor", "pregnant", "sport", "sportswear", "training", "transparent", "woman", "young"],
    ["donkey", "kick", "kicking", "plank", "woman"],
    ["down", "forward", "man", "neck", "plate", "prone", "resistance"],
    ["down", "knee", "lat", "modified", "plank", "woman"],
    ["down", "plank", "up", "woman"],
    ["dumbbell", "extension", "man", "overhead", "sitting", "tricep"],
    ["dumbbell", "extension", "man", "overhead", "tricep"],
    ["dumbbell", "extension", "man", "overhead", "tricep"],
    ["dumbbell", "extension", "man", "overhead", "tricep"],
    ["dumbbell", "extension", "prone", "tricep", "woman"],
    ["dumbbell", "extension", "tricep"],
    ["dumbbell", "extension", "tricep", "woman"],
    ["dumbbell", "floor", "folded", "man", "minimalistic", "row", "style", "up"],
    ["dumbbell", "flye", "folded", "lat", "lift", "man", "overhead", "up"],
    ["dumbbell", "flye", "folded", "man", "reverse", "up"],
    ["dumbbell", "folded", "lat", "man", "row", "up"],
    ["dumbbell", "folded", "man", "minimalistic", "row", "style", "up"],
    ["dumbbell", "folded", "row", "up", "woman"],
    ["dumbbell", "foot", "lift", "pullover", "woman"],
    ["dumbbell", "forward", "incline", "lift", "man"],
    ["dumbbell", "forward", "lift", "man"],
    ["dumbbell", "forward", "lift", "man"],
    ["dumbbell", "forward", "lift", "man", "shoulder", "single"],
    ["dumbbell", "forward", "lift", "shoulder", "single", "woman"],
    ["dumbbell", "forward", "lift", "shoulder", "single", "woman"],
    ["dumbbell", "forward", "lift", "woman"],
    ["dumbbell", "forward", "man", "shrug"],
    ["dumbbell", "four", "prisoner", "quad", "up", "woman"],
    ["dumbbell", "french", "man", "press", "sitting"],
    ["dumbbell", "french", "press", "sitting", "woman"],
    ["dumbbell", "hack", "man", "plate", "squat", "stepping"],
    ["dumbbell", "hang", "man", "snatch"],
    ["dumbbell", "head", "jerk", "lunging", "man", "split", "up"],
    ["dumbbell", "icon", "lunge", "man", "setu", "style"],
    ["dumbbell", "icon", "lunge", "setu", "style", "woman"],
    ["dumbbell", "internal", "laying", "man", "rotation", "shoulder"],
    ["dumbbell", "jump", "man", "squat"],
    ["dumbbell", "kickback", "man", "tricep"],
    ["dumbbell", "kickback", "tricep"],
    ["dumbbell", "kneeling", "setu", "squat", "woman"],
    ["dumbbell", "lat", "lift", "man", "partial", "shoulder", "strength"],
    ["dumbbell", "lat", "lift", "man", "partial", "sitting", "strength"],
    ["dumbbell", "lat", "lift", "partial", "shoulder", "strength", "woman"],
    ["dumbbell", "lat", "lift", "partial", "sitting", "strength", "woman"],
    ["dumbbell", "lat", "lift", "shoulder", "sitting", "woman"],
    ["dumbbell", "lunge", "man", "stepping"],
    ["dumbbell", "lunge", "man", "stepping"],
    ["dumbbell", "lunge", "punch", "woman"],
    ["dumbbell", "lunge", "stepping"],
    ["dumbbell", "machine", "press", "shoulder", "woman"],
    ["dumbbell", "man", "overhead", "press", "shoulder"],
    ["dumbbell", "man", "overhead", "press", "shoulder"],
    ["dumbbell", "man", "press", "push"],
    ["dumbbell", "man", "pullover"],
    ["dumbbell", "man", "pullover"],
    ["dumbbell", "man", "row", "standing"],
    ["dumbbell", "man", "squat"],
    ["dumbbell", "man", "step", "up"],
    ["dumbbell", "man", "stretch"],
    ["dumbbell", "man", "windshield", "wiper"],
    ["dumbbell", "martial", "overhead", "press", "shoulder", "sitting", "woman"],
    ["dumbbell", "overhead", "press", "shoulder", "woman"],
    ["dumbbell", "overhead", "press", "shoulder", "woman"],
    ["dumbbell", "overhead", "press", "squat", "thruster", "woman"],
    ["dumbbell", "row", "standing", "woman"],
    ["dumbbell", "russian", "twist"],
    ["dumbbell", "shrug", "woman"],
    ["dumbbell", "squat"],
    ["dumbbell", "step", "up", "woman"],
    ["dumbbell", "stretch", "up", "vest", "woman"],
    ["dynamic", "gate", "open", "opener", "standing", "stretch", "woman"],
    ["dynamic", "hamstring", "man", "stretch"],
    ["dynamic", "stretch"],
    ["eagle", "foot", "garudasana", "headstand", "pada", "salamba", "sirsasana", "stand", "woman"],
    ["elastic", "hamstring", "man", "strap", "stretch"],
    ["elastic", "hamstring", "strap", "stretch", "woman"],
    ["elbow", "knee", "press", "up", "woman"],
    ["elbow", "knee", "standing", "woman"],
    ["elbow", "lat", "plank", "rotation", "twist", "woman"],
    ["embryo", "garbha", "garbhasana", "pindasana", "stand", "woman", "yoga"],
    ["embryo", "man", "pindasana", "yoga"],
    ["embryo", "pindasana", "woman", "yoga"],
    ["era", "padasana", "prasarita", "split", "stand", "standing", "urdhva", "woman"],
    ["explosive", "man", "squat"],
    ["extension", "foot", "machine", "sitting", "woman"],
    ["extension", "hanging", "strap", "tricep", "trx", "woman"],
    ["external", "laying", "rotation", "shoulder", "woman"],
    ["eye", "man", "needle", "stand", "sucirandhrasana"],
    ["fast", "foot", "jog", "man"],
    ["fast", "foot", "woman"],
    ["fingertip", "jack", "toe", "woman"],
    ["flamingo", "humble", "stand", "woman", "yoga"],
    ["flexor", "hip", "kneeling", "man", "stretch"],
    ["flexor", "hip", "kneeling", "stretch", "woman"],
    ["flexor", "hip", "stretch", "woman"],
    ["floor", "jump", "knee", "squat", "strength", "woman"],
    ["floor", "lift", "woman"],
    ["foam", "lat", "man", "skater", "stretch"],
    ["foam", "lat", "skater", "stretch", "woman"],
    ["foam", "man", "neck", "release", "skater"],
    ["foam", "neck", "release", "skater", "woman"],
    ["foam", "quadricep", "skater", "stretch", "woman"],
    ["folded", "foot", "resistance", "strap", "stretch", "woman"],
    ["folded", "jump", "pulse", "squat", "woman"],
    ["folded", "press", "row", "up", "woman"],
    ["foot", "forward", "hip", "swing", "woman"],
    ["foot", "forward", "holding", "swing", "wall", "woman"],
    ["foot", "ham", "inner", "lat", "lift", "squeeze", "woman"],
    ["foot", "ham", "man", "stretching"],
    ["foot", "hanging", "lat", "lift", "man"],
    ["foot", "headstand", "ii", "konasana", "sirsasana", "stand", "tripod", "wide", "woman"],
    ["foot", "hip", "lat", "man", "swing"],
    ["foot", "hip", "lat", "swing", "woman"],
    ["foot", "hip", "rotation", "single", "stand", "woman"],
    ["foot", "hop", "hopping", "jump", "one", "single", "woman"],
    ["foot", "hop", "jump", "man", "one", "single"],
    ["foot", "hop", "jump", "one", "single", "woman"],
    ["foot", "ii", "lift", "plank", "step", "tutorial", "woman"],
    ["foot", "jack", "long", "plank", "woman"],
    ["foot", "karani", "stand", "stretch", "up", "viparita", "wall", "woman"],
    ["foot", "kettlebell", "man", "smashbell", "squat", "training"],
    ["foot", "kick", "lift", "machine", "man", "rear", "standing"],
    ["foot", "kickback", "single", "squat", "woman"],
    ["foot", "lat", "lift", "man", "squat"],
    ["foot", "lat", "lift", "woman"],
    ["foot", "lat", "swing", "woman"],
    ["foot", "legged", "man", "one", "push", "raised", "up"],
    ["foot", "legged", "one", "push", "raised", "up", "woman"],
    ["foot", "lift", "plank", "woman"],
    ["foot", "lift", "prone", "woman"],
    ["foot", "lift", "prone", "woman"],
    ["foot", "lift", "rear", "resistance", "strap", "woman"],
    ["foot", "loop", "woman"],
    ["foot", "machine", "man", "press"],
    ["foot", "man", "pistol", "single", "squat"],
    ["foot", "pistol", "single", "squat", "woman"],
    ["foot", "pistol", "single", "squat", "woman"],
    ["foot", "pistol", "single", "squat", "woman"],
    ["foot", "swing"],
    ["forearm", "kneeling", "man", "stretch", "wrist"],
    ["forearm", "kneeling", "stretch", "woman", "wrist"],
    ["forearm", "plank", "woman"],
    ["forward", "head", "kanu", "knee", "sirsasana", "stand", "twist", "woman"],
    ["forward", "high", "jog", "knee", "lift", "man", "stance"],
    ["forward", "high", "jog", "knee", "lift", "man", "stance"],
    ["forward", "high", "jog", "knee", "lift", "stance", "woman"],
    ["forward", "high", "jog", "knee", "lift", "stance", "woman"],
    ["forward", "kick", "lat", "plank", "woman"],
    ["forward", "kick", "lunge", "woman"],
    ["forward", "lat", "lift", "lunge", "woman"],
    ["forward", "lift", "long", "resistance", "strap", "woman"],
    ["forward", "man", "ragdoll", "stretch", "tuck", "twist"],
    ["forward", "paschimottanasana", "sitting", "twist", "woman"],
    ["forward", "ragdoll", "stretch", "tuck", "twist", "woman"],
    ["four", "good", "jump", "long", "man", "stand", "standing", "step"],
    ["four", "hamstring", "stretch", "woman"],
    ["frog", "jump", "man"],
    ["frog", "jump", "woman"],
    ["functional", "kick", "man", "sit"],
    ["garland", "malasana", "stand", "woman"],
    ["gate", "swing", "woman"],
    ["glute", "gluteus", "stretch", "woman"],
    ["glute", "man", "pigeon", "stretch"],
    ["glute", "pigeon", "stretch", "woman"],
    ["glute", "squeeze", "woman"],
    ["glute", "stretch"],
    ["goblet", "kettlebell", "squat", "woman"],
    ["goblet", "squat", "woman"],
    ["grip", "iso", "oblique", "palloff", "press", "woman"],
    ["grup", "lat", "man", "pulldown", "sitting", "wide"],
    ["guidance", "home", "lat", "lift", "man", "resistance", "strap", "thin"],
    ["hack", "man", "squat"],
    ["ham", "hamstring", "man", "standing", "stretch", "stretching"],
    ["ham", "inner", "lift", "woman"],
    ["hamstring", "hinge", "man", "stretch"],
    ["hamstring", "laying", "man", "prone", "stretch"],
    ["hamstring", "laying", "prone", "stretch", "woman"],
    ["hamstring", "man", "standing", "stretch"],
    ["hamstring", "standing", "stretch", "woman"],
    ["hamstring", "stretch", "woman"],
    ["hamstring", "stretch", "woman"],
    ["hand", "hastasana", "man", "salute", "stand", "tadasana", "upward", "urdhva", "volcano"],
    ["hand", "hastasana", "prep", "stand", "tree", "urdhva", "woman"],
    ["hand", "hastasana", "salute", "stand", "tadasana", "upward", "urdhva", "volcano", "woman"],
    ["hand", "man", "push", "staggered", "up"],
    ["handstand", "man", "push", "up"],
    ["hanging", "lunge", "man", "strap", "suspended", "trx"],
    ["hanging", "lunge", "strap", "suspended", "trx", "woman"],
    ["hanging", "man", "pike", "saw", "strap", "trx"],
    ["hasta", "konasana", "lift", "stand", "straddle", "upavistha", "woman", "yoga"],
    ["head", "janu", "knee", "parivrtta", "prep", "revolved", "sirsasana", "woman"],
    ["heavenly", "spirit", "stand", "standing", "stiti", "valakhilyasana", "woman", "yoga"],
    ["heisman", "ice", "jump", "lat", "shuffle", "skater", "woman"],
    ["high", "kick", "woman"],
    ["high", "knee"],
    ["home", "man", "resistance", "row", "standing", "strap", "thin"],
    ["hop", "lat", "man", "shuffle", "skater"],
    ["hop", "lat", "shuffle", "skater", "woman"],
    ["hop", "lat", "woman"],
    ["hug", "knee", "man", "standing"],
    ["hug", "knee", "standing", "woman"],
    ["hundred", "pilate", "woman"],
    ["inchworm", "woman"],
    ["incline", "push", "up", "woman"],
    ["internal", "laying", "man", "rotation", "shoulder"],
    ["internal", "laying", "rotation", "shoulder", "woman"],
    ["jack", "jump"],
    ["jack", "jump", "man", "plyo", "star"],
    ["jack", "jump", "man", "star"],
    ["jack", "jump", "modified", "woman"],
    ["jack", "jump", "woman"],
    ["jack", "lat", "man", "squat", "sumo", "walk"],
    ["jack", "lat", "squat", "sumo", "walk", "woman"],
    ["jack", "man", "seal", "sport"],
    ["jack", "man", "split"],
    ["jack", "seal", "sport", "woman"],
    ["jack", "squat", "woman"],
    ["jack", "woman"],
    ["jerk", "lat", "step", "woman"],
    ["jerk", "man", "rack"],
    ["jog", "stance", "woman"],
    ["jump", "knee", "man", "tuck"],
    ["jump", "knee", "tuck", "woman"],
    ["jump", "lat", "man", "squat"],
    ["jump", "lat", "squat", "woman"],
    ["jump", "lunge"],
    ["jump", "lunge", "man", "strength"],
    ["jump", "man", "snap"],
    ["jump", "man", "split", "squat"],
    ["jump", "man", "squat"],
    ["jump", "man", "squat", "tuck"],
    ["jump", "snap", "woman"],
    ["jump", "squat"],
    ["jump", "squat"],
    ["jump", "squat", "woman"],
    ["jump", "squat", "woman"],
    ["jump", "start", "woman"],
    ["jump", "tap", "woman"],
    ["kapotasana", "pigeon", "stand", "woman", "yoga"],
    ["kapotasana", "pigeon", "stand", "woman", "yoga"],
    ["katichakrasana", "man", "spinal", "stand", "standing", "twist"],
    ["kettlebell", "man", "swing"],
    ["kettlebell", "windmill", "woman"],
    ["kick", "kneeling", "roundhouse", "woman"],
    ["kick", "lat", "squat", "woman"],
    ["kick", "scissor", "woman"],
    ["kickback", "man", "resistance", "strap", "tricep"],
    ["kickback", "man", "tricep"],
    ["knee", "lift", "man", "step", "up"],
    ["knee", "lift", "step", "up", "woman"],
    ["knee", "lift", "step", "up", "woman"],
    ["knee", "man", "plank", "reach", "stand", "swimmer"],
    ["knee", "plank", "reach", "stand", "swimmer", "woman"],
    ["knee", "plank", "woman"],
    ["knee", "push", "up", "woman"],
    ["knee", "squat", "woman"],
    ["kurmasana", "reclining", "sleeping", "stand", "supta", "tortoise", "turtle", "woman"],
    ["laghu", "small", "stand", "thunderbolt", "vajrasana", "woman", "yoga"],
    ["landmine", "man", "press", "shoulder"],
    ["lat", "lift", "machine", "man", "partial", "sitting", "strength"],
    ["lat", "lift", "man", "resistance", "strap"],
    ["lat", "lift", "resistance", "strap", "woman"],
    ["lat", "man", "meditating", "neck", "release", "shoulder", "sitting", "stretching", "tension"],
    ["lat", "man", "resistance", "stepping", "strap"],
    ["lat", "meditating", "neck", "release", "shoulder", "sitting", "stretching", "tension", "woman"],
    ["lat", "plank", "rotation", "woman"],
    ["lat", "plank", "stand", "vasisthasana", "woman"],
    ["lat", "plank", "woman"],
    ["lat", "prone", "quad", "stretch", "woman"],
    ["lat", "shuffle", "woman"],
    ["lat", "squat", "woman"],
    ["lat", "stepping", "strap", "woman"],
    ["lizard", "pristhasana", "stand", "utthan", "woman"],
    ["long", "lunge", "resistance", "strap", "woman"],
    ["long", "puppy", "shishosana", "stand", "uttana", "woman", "yoga"],
    ["long", "resistance", "shoulder", "strap", "stretch", "woman"],
    ["long", "resistance", "strap", "stretch", "tricep", "woman"],
    ["lunge", "man", "overhead", "plate", "stepping"],
    ["lunge", "man", "powerbag", "sandbag", "stepping"],
    ["lunge", "man", "reverse", "trx"],
    ["lunge", "man", "stepping"],
    ["lunge", "man", "stretch"],
    ["lunge", "man", "twist"],
    ["lunge", "powerbag", "sandbag", "stepping", "woman"],
    ["lunge", "press", "reverse", "shoulder", "woman"],
    ["lunge", "punch", "woman"],
    ["lunge", "reverse", "shoulder", "squeeze", "woman"],
    ["lunge", "twist", "woman"],
    ["machine", "pilate", "reformer", "woman"],
    ["man", "matsyendrasana", "spinal", "stand", "supine", "supta", "twist"],
    ["man", "modified", "plank", "shoulder", "tap"],
    ["man", "oblique", "stretch"],
    ["man", "overhead", "pistol", "resistance", "squat", "strap"],
    ["man", "overhead", "plate", "press"],
    ["man", "overhead", "plate", "squat"],
    ["man", "overhead", "press", "resistance", "shoulder", "standing", "strap"],
    ["man", "overhead", "press", "sitting", "tricep"],
    ["man", "overhead", "stretch", "tricep"],
    ["man", "overhead", "stretch", "tricep"],
    ["man", "pike", "push", "up"],
    ["man", "piriformi", "stretch"],
    ["man", "plank", "up"],
    ["man", "press", "spider", "up"],
    ["man", "punch", "sitting"],
    ["man", "push", "sphinx", "up"],
    ["man", "push", "spider", "up", "woman"],
    ["man", "push", "up"],
    ["man", "push", "up", "viparita", "wall"],
    ["man", "pushed", "sled"],
    ["man", "quad", "standing", "stretch", "wall", "yoga"],
    ["man", "reverse", "shoulder", "stretch"],
    ["man", "sit", "suitcase", "up"],
    ["man", "sitting"],
    ["man", "skip", "strength"],
    ["man", "stretch", "up"],
    ["man", "tap", "toe"],
    ["man", "turkish", "up"],
    ["march", "stance", "woman"],
    ["mason", "russian", "sit", "twist", "woman"],
    ["matsyendrasana", "paripurna", "poorna", "sitting", "spinal", "stand", "twist", "woman"],
    ["mayurasana", "peacock", "stand", "woman", "yoga"],
    ["modified", "plank", "shoulder", "tap", "woman"],
    ["mudrasana", "salamba", "seal", "shoulderstand", "stand", "woman", "yoga"],
    ["neck", "stretch", "woman"],
    ["niralamba", "prep", "shoulderstand", "stand", "variation", "woman"],
    ["niralamba", "shoulder", "stand", "woman", "yoga"],
    ["niralamba", "shoulder", "stand", "woman", "yoga"],
    ["oblique", "stretch", "woman"],
    ["overhead", "press", "resistance", "strap", "woman"],
    ["parivrtta", "revolved", "stand", "thunderbolt", "vajrasana", "woman"],
    ["pawanmuktasana", "release", "stand", "wind", "woman"],
    ["phalakasana", "plank", "stand", "woman"],
    ["pigeon", "reverse", "stand", "sucirandhrasana", "woman"],
    ["pilate", "reformer", "woman"],
    ["plank", "renegade", "row", "woman"],
    ["plank", "spiderman", "woman"],
    ["plank", "tap", "toe", "woman"],
    ["plie", "scoop", "squat", "up", "woman"],
    ["pulse", "up", "woman"],
    ["push", "rotation", "up"],
    ["push", "spiderman", "up"],
    ["push", "squat", "woman"],
    ["pushed", "sled", "woman"],
    ["quad", "standing", "stretch", "woman"],
    ["quad", "stretch"],
    ["reclining", "saddle", "stand", "superman", "supta", "virasana", "woman"],
    ["reverse", "shoulder", "stretch", "woman"],
    ["row", "viparita", "woman"],
    ["russian", "twist", "woman"],
    ["scissor", "skier", "woman"],
    ["scorpion", "stretch", "woman"],
    ["shoulder", "stretch"],
    ["shrimp", "squat", "woman"],
    ["sit", "star", "tap", "toe", "up", "woman"],
    ["sit", "suitcase", "up", "woman"],
    ["sit", "up", "woman"],
    ["sit", "wall", "woman"],
    ["sitting", "stretch", "tap", "toe", "woman"],
    ["skater", "woman"],
    ["skip", "strength", "woman"],
    ["split", "squat", "woman"],
    ["split", "stand", "supine", "supta", "trivikramasana", "woman", "yoga"],
    ["squat", "stand", "sumo", "wide", "woman"],
    ["squat", "tip", "toe", "woman"],
    ["step", "stutter", "woman"],
    ["stretch", "tricep", "woman"],
    ["stretch", "trx", "up", "woman"],
    ["superman", "twist", "woman"],
    ["surrender", "woman"],
    ["tap", "toe", "woman"],
    ["trimmer", "waist", "woman"],
    ["woman"]
  ]
  ,
  "glossary": [
    "ab", "abdominal", "abduction", "abductor", "accomplished", "active", "activity", "adho", "admirable", "advanced", "against", "air",
    "alanasa", "alanasan", "alternating", "angel", "angle", "anjaneyasana", "ankle", "apanasana", "ardha", "arm", "arnold", "art",
    "asana", "ashwa", "assisted", "astonishing", "asymmetrical", "athlete", "awesome", "baby", "back", "background", "baddha", "bag",
    "bakasana", "balance", "ball", "banana", "bananasana", "band", "banded", "bandha", "bar", "barbell", "battle", "bear",
    "beautiful", "behind", "bell", "bellow", "bench", "bend", "bending", "bent", "bhastrika", "bhujang", "bhujangasana", "bicep",
    "bicycle", "bird", "block", "boat", "body", "bodybuilding", "bodyweight", "bosu", "bottle", "box", "boxer", "boxing",
    "boy", "breakdancer", "breath", "breathtaking", "bridge", "brilliant", "bug", "bulgarian", "burpee", "butterfly", "cable", "cage",
    "calf", "cardio", "cat", "chair", "chakrasana", "character", "chest", "child", "chin", "chop", "circle", "clean",
    "climber", "close", "cobra", "concentration", "control", "cool", "core", "cossack", "cow", "crab", "crawl", "cross",
    "crossover", "crow", "crucifix", "crunch", "crusher", "curl", "curling", "dancer", "dandasana", "day", "dead", "deadlift",
    "deck", "decline", "degree", "delt", "developer", "diagram", "diamond", "different", "dip", "dipping", "doe", "dog",
    "doign", "doing", "double", "down", "downward", "dumbbell", "during", "dynamic", "eagle", "editable", "elastic", "elbow",
    "elevated", "embryo", "equestrian", "equipment", "era", "excellent", "exceptional", "exercise", "exersice", "explosive", "extension", "external",
    "eye", "ez", "fabulous", "face", "fallen", "fantastic", "fast", "fetus", "figure", "file", "firming", "fitness",
    "five", "flamingo", "flat", "flexor", "floor", "flow", "flute", "fly", "flye", "foam", "fold", "folded",
    "foot", "forearm", "forward", "four", "free", "frog", "front", "full", "functional", "garbhasana", "garudasana", "gas",
    "gate", "german", "gironda", "glorious", "glute", "goblet", "gomukhasana", "good", "grappling", "grip", "grup", "guidance",
    "guide", "gym", "gymnastic", "hack", "halasana", "half", "ham", "hammer", "hamstring", "hand", "handstand", "hang",
    "hanging", "hatha", "head", "headstand", "health", "healthy", "heavenly", "heel", "hex", "high", "hiit", "hinge",
    "hip", "hold", "horizontal", "horse", "hug", "hundred", "icon", "ii", "illustrated", "illustration", "impressive", "in",
    "inchworm", "incline", "incredible", "inside", "introduction", "inverted", "isolated", "isometric", "jack", "jalandhara", "jathara", "jefferson",
    "jerk", "jog", "joint", "jump", "kapinjalasana", "kapotasana", "karani", "keep", "kettle", "kettlebell", "kick", "kickback",
    "knee", "kneeling", "konasana", "krounchasana", "laghu", "lat", "lateral", "laterally", "layer", "layered", "left", "leg",
    "legged", "liberation", "lifestyle", "lift", "lifting", "lolasana", "long", "loss", "lotus", "low", "lunge", "machine",
    "magnificent", "majestic", "man", "martial", "marvelous", "master", "matsyendrasana", "med", "medicine", "military", "minimalistic", "morning",
    "mountain", "mukha", "mukta", "muscle", "namaskar", "naukasana", "neck", "needle", "niralamba", "nw", "oblique", "octopus",
    "office", "old", "opposite", "overhead", "pack", "padangustha", "padangusthasana", "padmasana", "panna", "parallel", "paripurna", "parivrtti",
    "partial", "pec", "phalakasana", "physical", "picking", "pigeon", "pike", "pindasana", "pistol", "place", "plank", "plate",
    "plough", "plyo", "pointed", "pole", "pose", "position", "posture", "practice", "practicing", "pranayama", "prasarita", "preacher",
    "pregnant", "press", "prone", "pull", "pulldown", "pulling", "pullover", "pumping", "punch", "punching", "puppy", "push",
    "pushdown", "quadricep", "quick", "raise", "raised", "reach", "release", "remarkable", "renegade", "resistance", "reverse", "right",
    "ring", "roll", "roller", "rolling", "romanian", "rooster", "rope", "rotation", "row", "rowing", "run", "russian",
    "safe", "salamba", "sanchalanasana", "sarvangasana", "saw", "scissor", "seal", "seated", "self", "set", "setu", "shoulder",
    "shoulderstand", "shrug", "siddhasana", "side", "single", "sit", "sitting", "six", "skater", "skier", "skull", "slam",
    "small", "smash", "snake", "snatch", "soldier", "sphinx", "spider", "spiderman", "spinal", "splendid", "splendiferous", "split",
    "sport", "spot", "squat", "stable", "staff", "stance", "stand", "standing", "star", "start", "static", "stationary",
    "step", "stepping", "stiti", "straight", "strap", "strength", "stretch", "style", "sucirandhrasana", "sumo", "sunken", "superman",
    "supported", "supta", "surrender", "swelling", "swimmer", "swing", "swiss", "tail", "tap", "thigh", "through", "throughout",
    "thrust", "toe", "top", "touch", "training", "transparent", "treadmill", "trendy", "tri", "triangle", "trice", "tricep",
    "tripod", "trivikramasana", "tuck", "turn", "turning", "tutorial", "twine", "twist", "twisted", "twisting", "unbelievable", "unsupported",
    "until", "up", "upper", "upperbody", "using", "ustrasana", "valakhilyasana", "variation", "vasisthasana", "vector", "view", "viparita",
    "walking", "wall", "water", "weight", "weighted", "white", "wind", "windshield", "wiper", "woman", "wonderful", "wood",
    "working", "workout", "wrist", "yoga"
  ]
}

###
GET {{host}}/models
Content-Type: application/json

###
POST {{host}}/train_model
Content-Type: application/json

{
  "name": "model1",
  "training_data": [
      [ ["man", "jump", "jack", "star"], ["man", "jump", "jack", "star"] ],
      [ ["woman", "jump", "jack", "star"], ["woman", "jump", "jack"] ],
      [ ["man", "arm", "circle"], ["man", "arm", "circle"] ],
      [ ["woman", "arm", "circle"], ["woman", "arm", "circle"] ],
      [ ["man", "bodyweight", "squat"], ["man", "bodyweight", "squat"] ],
      [ ["woman", "bodyweight", "squat"], ["woman", "bodyweight", "squat"] ],
      [ ["man", "high", "knee"], ["man", "high", "knee", "wall", "against"] ],
      [ ["woman", "high", "knee"], ["woman", "high", "knee", "forward", "lift", "jog", "stance"] ],
      [ ["man", "dynamic", "stretch"], ["man", "dynamic", "hamstring", "stretch"] ],
      [ ["woman", "dynamic", "stretch"], ["woman", "standing", "open", "gate", "dynamic", "stretch", "opener"] ],
      [ ["man", "burpee"], ["man", "chest", "floor", "burpee"] ],
      [ ["woman", "burpee"], ["woman", "burpee"] ],
      [ ["man", "mountain", "climber"], ["man", "mountain", "climber"] ],
      [ ["woman", "mountain", "climber"], ["woman", "mountain", "climber"] ],
      [ ["man", "jump", "squat"], ["man", "jump", "squat"] ],
      [ ["woman", "jump", "squat"], ["woman", "jump", "squat"] ],
      [ ["man", "push", "up", "rotation"], ["man", "push", "up"] ],
      [ ["woman", "push", "up", "rotation"], ["push", "up", "rotation"] ],
      [ ["man", "russian", "twist", "dumbbell"], ["russian", "twist", "dumbbell"] ],
      [ ["woman", "russian", "twist", "dumbbell"], ["russian", "twist", "dumbbell"] ],
      [ ["man", "jump", "lunge"], ["man", "alternating", "lunge", "jump"] ],
      [ ["woman", "jump", "lunge"], ["woman", "explosive", "jump", "alternating", "lunge", "step", "four", "lower", "body", "hamstring"] ],
      [ ["man", "shoulder", "stretch"], ["man", "reverse", "shoulder", "stretch"] ],
      [ ["woman", "shoulder", "stretch"], ["woman", "shoulder", "stretch", "long", "resistance", "strap"] ],
      [ ["man", "quad", "stretch"], ["man", "standing", "quad", "stretch", "yoga", "wall"] ],
      [ ["woman", "quad", "stretch"], ["woman", "standing", "quad", "stretch"] ],
      [ ["man", "hamstring", "stretch"], ["man", "hamstring", "stretch", "elastic", "strap"] ],
      [ ["woman", "hamstring", "stretch"], ["woman", "hamstring", "stretch"] ],
      [ ["man", "child", "stand"], ["man", "child", "stand", "stretch"] ],
      [ ["woman", "child", "stand"], ["woman", "child", "stand", "stretch"] ],
      [ ["man", "jump", "squat"], ["man", "jump", "squat"] ],
      [ ["woman", "jump", "squat"], ["woman", "jump", "squat"] ],
      [ ["man", "foot", "swing"], ["man", "lat", "foot", "hip", "swing"] ],
      [ ["woman", "foot", "swing"], ["woman", "lat", "foot", "swing"] ],
      [ ["man", "butt", "kick"], ["man", "butt", "kick", "character", "setu"] ],
      [ ["woman", "butt", "kick"], ["butt", "kick"] ],
      [ ["man", "air", "squat"], ["man", "air", "squat", "ii", "step", "forward"] ],
      [ ["woman", "air", "squat"], ["air", "squat"] ],
      [ ["man", "glute", "bridge"], ["man", "bench", "glute", "bridge", "bar"] ],
      [ ["woman", "glute", "bridge"], ["woman", "chest", "flye", "glute", "bridge"] ],
      [ ["man", "dip"], ["man", "dip", "parallel", "bar", "gym"] ],
      [ ["woman", "dip"], ["woman", "trice", "dip"] ],
      [ ["man", "tricep", "extension", "dumbbell"], ["man", "dumbbell", "overhead", "tricep", "extension"] ],
      [ ["woman", "tricep", "extension", "dumbbell"], ["woman", "dumbbell", "tricep", "extension"] ],
      [ ["man", "diamond", "push", "up"], ["man", "diamond", "push", "up", "four", "tricep", "chest"] ],
      [ ["woman", "diamond", "push", "up"], ["woman", "diamond", "pyramid", "push", "up"] ],
      [ ["man", "tricep", "kickback", "dumbbell"], ["man", "tricep", "kickback", "dumbbell"] ],
      [ ["woman", "tricep", "kickback", "dumbbell"], ["tricep", "kickback", "dumbbell"] ],
      [ ["man", "squat", "dumbbell"], ["man", "squat", "dumbbell"] ],
      [ ["woman", "squat", "dumbbell"], ["woman", "dumbbell", "kneeling", "squat", "setu"] ],
      [ ["man", "stepping", "lunge", "dumbbell"], ["man", "dumbbell", "stepping", "lunge"] ],
      [ ["woman", "stepping", "lunge", "dumbbell"], ["woman", "body", "dumbbell", "stepping", "lunge"] ],
      [ ["man", "step", "up", "plyo", "boxing", "dumbbell"], ["step", "up", "plyo", "boxing", "dumbbell"] ],
      [ ["woman", "step", "up", "plyo", "boxing", "dumbbell"], ["step", "up", "plyo", "boxing", "dumbbell"] ],
      [ ["man", "glute", "stretch"], ["man", "pigeon", "glute", "stretch"] ],
      [ ["woman", "glute", "stretch"], ["woman", "gluteus", "glute", "stretch"] ],
      [ ["man", "bosu", "ball", "bridge", "hip", "lift", "glute"], ["man", "bosu", "ball", "bridge", "hip", "lift", "glute"] ],
      [ ["woman", "bosu", "ball", "bridge", "hip", "lift", "glute"], ["woman", "bosu", "ball", "bridge", "hip", "lift", "glute"] ],
      [ ["man", "supine", "spinal", "twist"], ["man", "supta", "matsyendrasana", "supine", "spinal", "twist", "stand"] ],
      [ ["woman", "supine", "spinal", "twist"], ["woman", "supine", "spinal", "twist", "stand", "ii", "supta", "abdominal", "jathara", "parivartanasana"] ],
      [ ["man", "warm", "up", "hip", "circle"], ["man", "hip", "lift", "butt", "bridge", "curling", "shoulder", "reach", "bodyweight"] ],
      [ ["woman", "warm", "up", "hip", "circle"], ["woman", "hip", "circle"] ],
      [ ["man", "jump", "rope"], ["man", "jump", "rope", "cardio"] ],
      [ ["woman", "jump", "rope"], ["woman", "jump", "rope", "cardio"] ],
      [ ["man", "standing", "dumbbell", "shoulder", "press"], ["man", "dumbbell", "overhead", "shoulder", "press", "body"] ],
      [ ["woman", "standing", "dumbbell", "shoulder", "press"], ["woman", "shoulder", "press", "dumbbell", "machine"] ],
      [ ["man", "lat", "lift"], ["man", "lat", "lift", "resistance", "strap"] ],
      [ ["woman", "lat", "lift"], ["woman", "lat", "lift", "resistance", "strap"] ],
      [ ["man", "folded", "up", "reverse", "flye"], ["man", "dumbbell", "folded", "up", "reverse", "flye"] ],
      [ ["woman", "folded", "up", "reverse", "flye"], ["woman", "dumbbell", "folded", "up", "chest", "salamba", "reverse", "flye"] ],
      [ ["man", "bicep", "curl"], ["man", "dumbbell", "bicep", "hammer", "curl", "different", "layer", "character"] ],
      [ ["woman", "bicep", "curl"], ["woman", "bicep", "curl"] ],
      [ ["man", "tricep", "dip"], ["man", "bench", "tricep", "dip"] ],
      [ ["woman", "tricep", "dip"], ["woman", "bench", "tricep", "dip"] ],
      [ ["man", "hammer", "curl"], ["man", "cable", "hammer", "bicep", "curl", "arm"] ],
      [ ["woman", "hammer", "curl"], ["woman", "hammer", "hand", "curl", "long", "resistance", "strap"] ],
      [ ["man", "dumbbell", "press"], ["man", "dumbbell", "push", "press"] ],
      [ ["woman", "dumbbell", "press"], ["woman", "dumbbell", "chest", "press"] ],
      [ ["man", "dumbbell", "flye"], ["man", "bench", "dumbbell", "flye", "overhead"] ],
      [ ["woman", "dumbbell", "flye"], ["woman", "dumbbell", "folded", "up", "chest", "salamba", "reverse", "flye"] ],
      [ ["man", "push", "up"], ["man", "push", "up"] ],
      [ ["woman", "push", "up"], ["woman", "asymmetrical", "push", "up"] ],
      [ ["man", "dynamic", "chest", "stretch"], ["man", "chest", "stretch", "wall", "standing", "one", "arm"] ],
      [ ["woman", "dynamic", "chest", "stretch"], ["woman", "chest", "stretch"] ],
      [ ["man", "shrug", "stretch"], ["man", "stretch", "up"] ],
      [ ["woman", "shrug", "stretch"], ["woman", "stretch", "up", "machine", "assisted"] ],
      [ ["man", "chest", "stretch"], ["man", "chest", "stretch", "wall", "standing", "one", "arm"] ],
      [ ["woman", "chest", "stretch"], ["woman", "chest", "stretch"] ],
      [ ["man", "tricep", "stretch"], ["man", "overhead", "tricep", "stretch"] ],
      [ ["woman", "tricep", "stretch"], ["woman", "tricep", "stretch"] ],
      [ ["man", "bicep", "stretch"], ["man", "stretch", "up"] ],
      [ ["woman", "bicep", "stretch"], ["woman", "bicep", "stretch"] ],
      [ ["man", "bench", "jump", "up"], ["man", "bench", "hop", "boxing", "jump", "up", "sport"] ],
      [ ["woman", "bench", "jump", "up"], ["woman", "sitting", "bench", "foot", "stretch", "knee", "up"] ],
      [ ["man", "warm", "up", "stepping"], ["man", "plank", "push", "up", "movement", "stepping", "down", "ab"] ],
      [ ["woman", "warm", "up", "stepping"], ["woman", "bosu", "ball", "plank", "push", "up", "stepping", "down"] ],
      [ ["man", "warm", "up", "hip", "circle"], ["man", "hip", "lift", "butt", "bridge", "curling", "shoulder", "reach", "bodyweight"] ],
      [ ["woman", "warm", "up", "hip", "circle"], ["woman", "hip", "circle"] ],
      [ ["man", "plank", "row", "weight"], ["man", "plank", "abdominal"] ],
      [ ["woman", "plank", "row", "weight"], ["woman", "plank", "row", "renegade"] ],
      [ ["man", "lat", "plank"], ["man", "lat", "plank", "abdominal"] ],
      [ ["woman", "lat", "plank"], ["woman", "lat", "plank"] ],
      [ ["man", "deadlift", "weight"], ["man", "dumbbell", "deadlift"] ],
      [ ["woman", "deadlift", "weight"], ["woman", "dumbbell", "deadlift"] ],
      [ ["man", "superman"], ["man", "sitting"] ],
      [ ["woman", "superman"], ["woman", "superman", "twist"] ],
      [ ["man", "quadricep", "stretch"], ["man", "quadricep", "stretch", "cool", "down", "swing", "stand", "flexibility", "improvement"] ],
      [ ["woman", "quadricep", "stretch"], ["woman", "foam", "skater", "quadricep", "stretch"] ],
      [ ["man", "ischio", "stretch"], ["man", "stretch", "up"] ],
      [ ["woman", "ischio", "stretch"], ["woman", "stretch", "up", "machine", "assisted"] ],
      [ ["man", "shrug", "stretch"], ["man", "stretch", "up"] ],
      [ ["woman", "shrug", "stretch"], ["woman", "stretch", "up", "machine", "assisted"] ],
      [ ["man", "upperbody", "twist"], ["man", "twist", "abdominal", "excercise"] ],
      [ ["woman", "upperbody", "twist"], ["woman", "bridge", "twist"] ],
      [ ["man", "crunch"], ["man", "crunch", "abdominal"] ],
      [ ["woman", "crunch"], ["woman", "crunch", "chop"] ],
      [ ["man", "prone", "foot", "lift"], ["man", "prone", "foot", "lift", "abdominal", "body", "dumbbell"] ],
      [ ["woman", "prone", "foot", "lift"], ["woman", "prone", "foot", "lift"] ],
      [ ["man", "reverse", "crunch"], ["man", "incline", "bench", "reverse", "crunch"] ],
      [ ["woman", "reverse", "crunch"], ["woman", "crunch", "chop"] ],
      [ ["man", "foot", "lift"], ["man", "hanging", "foot", "lift", "lat", "abdominal"] ],
      [ ["woman", "foot", "lift"], ["woman", "prone", "foot", "lift"] ],
      [ ["man", "plank", "foot", "lift"], ["man", "hanging", "foot", "lift", "lat", "abdominal"] ],
      [ ["woman", "plank", "foot", "lift"], ["woman", "plank", "foot", "lift"] ],
      [ ["man", "bicycle", "crunch"], ["man", "crunch", "abdominal"] ],
      [ ["woman", "bicycle", "crunch"], ["woman", "crunch", "chop"] ],
      [ ["man", "bhujang", "stretch"], ["man", "bhujang", "ab", "stretch", "old", "ashwa", "abdominal"] ],
      [ ["woman", "bhujang", "stretch"], ["woman", "bhujang", "lat", "pulldown"] ],
      [ ["man", "sitting", "oblique", "stretch"], ["man", "oblique", "stretch"] ],
      [ ["woman", "sitting", "oblique", "stretch"], ["woman", "oblique", "stretch"] ],
      [ ["man", "sitting", "overhead", "dumbbell", "tricep", "extension"], ["man", "sitting", "overhead", "dumbbell", "tricep", "extension"] ],
      [ ["woman", "man", "sitting", "overhead", "dumbbell", "tricep", "extension"], ["man", "sitting", "overhead", "dumbbell", "tricep", "extension"] ],
      [ ["man", "stretching", "hip", "circle"], ["man", "lat", "bend", "stretching", "hand", "hip", "sport"] ],
      [ ["woman", "stretching", "hip", "circle"], ["woman", "hip", "circle"] ],
      [ ["man", "forearm", "plank"], ["man", "plank", "abdominal"] ],
      [ ["woman", "forearm", "plank"], ["woman", "forearm", "plank"] ],
      [ ["man", "dead", "bug"], ["man", "dead", "bug", "abdominal", "editable", "file", "layer"] ],
      [ ["woman", "dead", "bug"], ["woman", "dead", "bug", "abdominal", "editable", "file", "layer"] ],
      [ ["man", "pigeon", "puppy"], ["man", "pigeon", "puppy", "alternating", "reach", "kickback", "stand", "four", "six", "pack"] ],
      [ ["woman", "pigeon", "puppy"], ["woman", "pigeon", "puppy", "alternating", "reach", "kickback"] ],
      [ ["man", "viparita", "row", "parallel", "bar"], ["man", "dip", "parallel", "bar", "gym"] ],
      [ ["woman", "viparita", "row", "parallel", "bar"], ["woman", "viparita", "row"] ],
      [ ["man", "resistance", "strap", "row"], ["man", "standing", "row", "home", "thin", "resistance", "strap"] ],
      [ ["woman", "resistance", "strap", "row"], ["woman", "resistance", "strap", "crab", "stepping"] ],
      [ ["man", "single", "arm", "dumbbell", "row"], ["man", "single", "arm", "folded", "up", "row", "character", "setu"] ],
      [ ["woman", "single", "arm", "dumbbell", "row"], ["woman", "single", "arm", "dumbbell", "overhead", "shoulder", "press", "character", "setu"] ],
      [ ["man", "dumbbell", "deadlift"], ["man", "dumbbell", "deadlift"] ],
      [ ["woman", "dumbbell", "deadlift"], ["woman", "dumbbell", "deadlift"] ],
      [ ["man", "dumbbell", "pullover"], ["man", "dumbbell", "pullover"] ],
      [ ["woman", "dumbbell", "pullover"], ["woman", "dumbbell", "pullover", "foot", "lift"] ],
      [ ["man", "renegade", "row", "dumbbell"], ["man", "standing", "dumbbell", "row"] ],
      [ ["woman", "renegade", "row", "dumbbell"], ["woman", "renegade", "row", "adho", "puppy", "tap", "plank"] ],
      [ ["man", "back", "stretch"], ["man", "standing", "reach", "up", "back", "rotation", "stretch"] ],
      [ ["woman", "back", "stretch"], ["woman", "sport", "superman", "stretch", "four", "back", "ab", "dumbbell", "loss"] ],
      [ ["man", "cat", "cow", "stretch"], ["man", "yoga", "cat", "cow", "stand", "stretch"] ],
      [ ["woman", "cat", "cow", "stretch"], ["woman", "yoga", "cat", "cow", "stretch"] ],
      [ ["man", "sit", "up"], ["man", "sit", "up", "abdominal"] ],
      [ ["woman", "sit", "up"], ["woman", "sit", "up"] ],
      [ ["man", "scissor", "kick"], ["man", "functional", "kick", "sit"] ],
      [ ["woman", "scissor", "kick"], ["woman", "scissor", "kick"]
      ]
    ]
}

###
POST {{host}}/search
Content-Type: application/json

{
  "name": "model1",
  "vector": ["jump", "squat"]
}

###
GET {{host}}/version
Content-Type: application/json