###
POST {{host}}/create_model
Content-Type: application/json

{
  "name": "model1",
  "dictionary": [
  ["wind", "squat"],
  ["burpee"],
  ["butt", "kick"],
  ["child", "stand"],
  ["concept", "design", "woman", "stepping", "four", "cardio", "training", "design"],
  ["diamond", "push", "up"],
  ["dip"],
  ["dynamic", "stretch"],
  ["practice", "tutorial", "woman", "plank", "leg", "raise", "ii", "step", "isolated"],
  ["practice", "tutorial", "woman", "squat", "push", "burpee", "stand", "step", "workout", "diagram"],
  ["fitness", "workout", "woman", "sport", "practice", "superman", "stretch", "workout", "four", "back", "ab", "fitness", "four", "kettlebell", "loss", "isolated"],
  ["fitness", "woman", "martial", "art", "punch", "art", "gym", "woman", "athlete", "training", "low", "punching", "bag", "boxing", "gym", "woman", "boxer", "fitness", "gym"],
  ["butt", "bridge"],
  ["butt", "bridge", "kettlebell"],
  ["butt", "stretch"],
  ["ardha", "handstand", "art", "wall", "lat", "plank", "variation", "ardha", "handstand", "art", "wall", "woman", "practice", "kapinjalasana", "vasisthasana", "variation", "hand", "toe", "knee", "folded"],
  ["high", "knee"],
  ["illustrated", "practice", "tutorial", "healthy", "man", "lunge", "workout", "ii", "step", "four", "firming", "glute", "leg"],
  ["illustrated", "practice", "tutorial", "healthy", "woman", "lunge", "workout", "ii", "step", "four", "firming", "glute", "leg"],
  ["man", "practice", "kettlebell", "step", "up", "bench", "isolated"],
  ["jumping", "jack"],
  ["jumping", "lunge"],
  ["jumping", "squat"],
  ["hop", "squat"],
  ["knee", "plank", "practice", "isolated", "layered", "workout", "character"],
  ["leg", "swing"],
  ["man", "arm", "ring"],
  ["man", "bodyweight", "squat"],
  ["man", "cable", "push", "chest", "practice", "isolated", "mukta"],
  ["man", "character", "kettlebell", "incline", "bench", "row", "practice"],
  ["man", "four", "step", "muscle", "up", "bar", "calisthenic", "movement"],
  ["man", "degree", "rolling", "lunge", "rotation", "lunge", "practice"],
  ["man", "ab", "practice", "stand", "introduction", "plank", "knee", "elbow", "overhead", "forward", "tutorial", "hiit", "workout"],
  ["man", "accomplished", "siddhasana", "yoga", "practice"],
  ["man", "dynamic", "hamstring", "stretch", "practice", "isolated"],
  ["man", "advanced", "tuck", "forward", "raise", "bar", "calisthenic", "practice"],
  ["man", "wind", "squat", "ii", "step", "forward", "isolated"],
  ["man", "alternating", "kettlebell", "curl", "isolated", "different", "layer", "training", "character"],
  ["man", "alternating", "lunge", "hop", "practice", "isolated"],
  ["man", "anjaneyasana", "low", "lunge", "yoga", "stand", "trendy", "style", "mukta"],
  ["man", "ankle", "ring", "rotation", "roll", "practice", "isolated"],
  ["man", "archer", "stretch", "up", "calisthenic", "practice"],
  ["man", "arnold", "press", "practice", "isolated", "mukta"],
  ["man", "assisted", "machine", "sitting", "tricep", "dip", "practice", "isolated"],
  ["man", "back", "raise", "calisthenic", "stand"],
  ["man", "banana", "stand", "bananasana", "practice"],
  ["man", "banded", "opposite", "lat", "flye", "practice"],
  ["man", "kettlebell", "bench", "press", "chest", "press", "isolated", "mukta"],
  ["man", "kettlebell", "folded", "up", "row", "practice", "lat", "isolated"],
  ["man", "kettlebell", "clean", "boxing", "clean", "block", "clean", "practice"],
  ["man", "kettlebell", "deadlift", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "forward", "raise", "practice", "isolated"],
  ["man", "kettlebell", "hack", "squat", "stepping", "kettlebell", "plate"],
  ["man", "kettlebell", "up", "head", "lunging", "split", "jerk"],
  ["man", "kettlebell", "pullover", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "opposite", "wrist", "curl", "bench", "practice", "forearm", "practice"],
  ["man", "kettlebell", "romanian", "deadlift", "practice"],
  ["man", "kettlebell", "shrug", "back", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "windshield", "wiper", "practice", "isolated"],
  ["man", "battle", "rope", "folded", "arm", "slam", "practice", "isolated"],
  ["man", "bear", "crawl", "practice", "introduction", "step", "healthy", "man", "isolated"],
  ["man", "behind", "back", "standing", "wrist", "curl", "practice", "isolated"],
  ["man", "bellow", "breath", "bhastrika", "pranayama", "yoga", "practice"],
  ["man", "bench", "cable", "flye", "chest", "day", "practice", "isolated"],
  ["man", "bench", "butt", "bridge", "bar", "practice"],
  ["man", "bench", "hop", "boxing", "hop", "bench", "hop", "up", "sport", "practice", "isolated"],
  ["man", "bench", "pike", "push", "up", "practice"],
  ["man", "bench", "swiss", "fitness", "workout", "practicing", "ab", "practice", "med", "ball", "art", "gym", "russian", "twist", "med", "ball", "isolated"],
  ["man", "bench", "tricep", "dip", "isolated"],
  ["man", "bench", "tricep", "dip"],
  ["man", "folded", "up", "kettlebell", "row", "practice", "kettlebell", "minimalistic", "style", "isolated"],
  ["man", "folded", "up", "kettlebell", "row", "floor", "practice", "kettlebell", "minimalistic", "style", "isolated"],
  ["man", "folded", "up", "single", "arm", "banded", "row", "practice"],
  ["man", "folded", "up", "bar", "row", "overhead", "body", "workout", "overhead", "body", "practice", "isolated"],
  ["man", "pigeon", "puppy", "practice", "alternating", "reach", "kickback", "stand", "four", "six", "pack", "isolated"],
  ["man", "body", "crunch", "standing", "crucifix", "practice", "man", "ab", "practice", "tutorial"],
  ["man", "bodyweight", "martial", "press", "overhead", "shoulder", "press", "practice"],
  ["man", "bosu", "ball", "bridge", "hip", "raise", "butt", "bridge", "practice", "isolated"],
  ["man", "bosu", "ball", "mountain", "climber", "abdominal", "practice", "isolated"],
  ["man", "bosu", "ball", "plank", "push", "up", "stepping", "plank", "up", "down", "practice", "isolated"],
  ["man", "bosu", "ball", "static", "handstand", "isolated"],
  ["man", "bound", "angel", "stand", "baddha", "konasana", "practice"],
  ["man", "bound", "lotus", "baddha", "padmasana", "practice"],
  ["man", "boxing", "pike", "grip", "practice", "pike", "push", "up", "boxing"],
  ["man", "bridge", "stand", "setu", "bandha", "shoulderstand", "practice", "isolated"],
  ["man", "bridge", "stand", "setu", "bandha", "shoulderstand", "wall", "practice", "isolated"],
  ["man", "bulgarian", "split", "squat", "practice", "isolated", "mukta"],
  ["man", "butt", "kick", "practice", "isolated", "workout", "character", "setu"],
  ["man", "butterfly", "pec", "deck", "sitting", "machine", "flye", "isolated"],
  ["man", "cable", "folded", "up", "tricep", "extension", "practice"],
  ["man", "cable", "ab", "rotation", "abdominal", "practice", "isolated"],
  ["man", "cable", "forward", "stretch", "practice", "shoulder", "practice", "mukta"],
  ["man", "cable", "hammer", "bicep", "curl", "practice", "arm", "workout", "fitness", "man", "isolated"],
  ["man", "cable", "hip", "extension", "practice", "isolated"],
  ["man", "cable", "stretch", "practice", "isolated"],
  ["man", "cable", "rope", "pushdown", "practice", "isolated", "mukta"],
  ["man", "cable", "squat", "row", "practice", "isolated", "backgound", "row", "squat"],
  ["man", "calisthenic", "weighted", "chin", "up", "practice"],
  ["man", "cat", "tail", "pulling", "stand", "practice", "cat", "tail", "pulling", "stand", "isolated"],
  ["man", "chair", "bench", "tricep", "dip", "practice", "isolated"],
  ["man", "chair", "stand", "practice", "isolated"],
  ["man", "chair", "sitting", "neck", "turn", "head", "rotation", "neck", "rotation", "practice", "rolling", "head", "left", "right", "healthy", "activity", "office", "stretch"],
  ["man", "chair", "squat", "practice", "partial", "ardha", "squat", "chair", "four", "athlete"],
  ["man", "chest", "stretch", "practice", "wall", "standing", "one", "arm", "chest", "stretch"],
  ["man", "chest", "floor", "burpee", "practice", "isolated"],
  ["man", "child", "stand", "stretch", "practice", "mukta"],
  ["man", "chin", "up", "workout", "fitness", "bodybuilding", "practice", "gym", "healthy", "dynamic", "lifestyle", "isolated"],
  ["man", "close", "hand", "bench", "press", "practice", "isolated", "mukta"],
  ["man", "close", "hand", "lat", "pulldown", "isolated"],
  ["man", "bhujang", "ab", "stretch", "old", "horse", "stretch", "abdominal", "practice", "isolated"],
  ["man", "cossack", "squat", "practice"],
  ["man", "cow", "forward", "stand", "gomukhasana", "practice", "isolated"],
  ["man", "crab", "toe", "touch", "practice", "isolated"],
  ["man", "crucifix", "back", "lunge", "practice"],
  ["man", "crow", "stand", "bakasana", "practice", "isolated"],
  ["man", "crunch", "abdominal", "practice", "isolated"],
  ["man", "dead", "bug", "practice", "abdominal", "practice", "isolated", "editable", "file", "layer"],
  ["man", "decline", "crunch", "bench", "practice"],
  ["man", "diamond", "push", "up", "practice", "four", "tricep", "chest", "isolated"],
  ["man", "diamond", "push", "up", "practice", "four", "tricep", "chest"],
  ["man", "dipping", "pigeon", "practice"],
  ["man", "dip", "parallel", "bar", "gym", "practice", "isolated"],
  ["man", "folded", "arm", "lat", "lat", "raise", "practice", "raise", "arm", "laterally", "until", "horizontal", "isolated"],
  ["man", "folded", "arm", "lat", "lat", "raise", "overhead", "extension", "practice", "isolated"],
  ["man", "folded", "crunch", "abdominal", "practice", "isolated"],
  ["man", "kettlebell", "folded", "up", "chest", "salamba", "opposite", "flye"],
  ["man", "kettlebell", "folded", "up", "lat", "raise", "overhead", "flye", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "folded", "up", "opposite", "flye", "isolated", "mukta"],
  ["man", "kettlebell", "bicep", "hammer", "curl", "isolated", "different", "layer", "workout", "character", "mukta"],
  ["man", "kettlebell", "bicep", "hammer", "curl", "isolated", "different", "layer", "training", "character"],
  ["man", "kettlebell", "concentration", "curl", "isolated", "different", "layer", "workout", "character", "mukta"],
  ["man", "kettlebell", "deadlift", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "bench", "chest", "press", "practice", "isolated"],
  ["man", "kettlebell", "forward", "raise", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "hang", "snatch", "practice"],
  ["man", "kettlebell", "hop", "squat", "practice"],
  ["man", "kettlebell", "lunge", "setu", "workout", "icon", "style", "isolated", "mukta"],
  ["man", "kettlebell", "overhead", "shoulder", "press", "overhead", "body", "workout", "overhead", "body", "practice", "isolated"],
  ["man", "kettlebell", "overhead", "shoulder", "press", "overhead", "body", "training", "practice", "isolated"],
  ["man", "kettlebell", "overhead", "tricep", "extension", "practice", "isolated"],
  ["man", "kettlebell", "overhead", "tricep", "extension", "practice", "isolated"],
  ["man", "kettlebell", "stretch", "practice", "isolated"],
  ["man", "kettlebell", "pullover", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "push", "press", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "shrug", "forward", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "step", "up", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "stepping", "lunge", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "stepping", "lunge", "practice", "isolated", "mukta"],
  ["man", "kettlebell", "weighted", "leg", "stretch", "abdominal", "practice", "isolated"],
  ["man", "kettlebell", "wood", "chop", "practice"],
  ["man", "high", "kettlebell", "butt", "bridge", "hip", "raise", "practice", "isolated"],
  ["man", "embryo", "pindasana", "yoga", "practice"],
  ["man", "equestrian", "ashwa", "sanchalanasana", "practice"],
  ["man", "practice", "opposite", "lunge", "stand", "water", "bottle"],
  ["man", "practice", "standing", "long", "jumping", "stand", "step", "step", "fitness", "stand", "four", "good", "practice"],
  ["man", "practice", "using", "abductor", "thigh", "machine", "abductor", "workout"],
  ["man", "practice", "using", "gym", "equipment", "sitting", "calf", "machine", "raise", "isolated"],
  ["man", "explosive", "squat", "practice", "isolated"],
  ["man", "external", "rotation", "bodyweight", "calf", "raise", "practice", "isolated"],
  ["man", "eye", "needle", "stand", "sucirandhrasana", "practice", "isolated"],
  ["man", "ez", "bar", "overhead", "hand", "tricep", "extension", "practice"],
  ["man", "quick", "foot", "run", "practice"],
  ["man", "character", "four", "stretch", "practice", "mukta"],
  ["man", "bench", "kettlebell", "head", "crusher", "practice", "isolated", "mukta"],
  ["man", "bench", "kettlebell", "flye", "practice", "overhead", "isolated", "mukta"],
  ["man", "floor", "tricep", "dip", "practice"],
  ["man", "foam", "skater", "lat", "stretch", "practice"],
  ["man", "foam", "skater", "neck", "liberation", "practice"],
  ["man", "forward", "forward", "shoulder", "single", "kettlebell", "raise", "practice", "isolated"],
  ["man", "frog", "hop", "practice", "isolated", "mukta"],
  ["man", "forward", "incline", "kettlebell", "raise", "practice"],
  ["man", "forward", "raise", "bar", "calisthenic", "practice"],
  ["man", "paripurna", "kettlebell", "clean", "press", "jerk", "overhead", "press"],
  ["man", "functional", "kick", "sit", "practice", "isolated"],
  ["man", "gironda", "dip", "practice", "isolated", "workout", "character", "setu"],
  ["man", "butt", "ham", "raise", "practice", "butt", "ham", "developer", "back", "extension"],
  ["man", "gymnastic", "ring", "grip", "abdominal", "practice", "isolated", "editable", "file", "layer"],
  ["man", "hack", "squat", "practice", "isolated"],
  ["man", "hamstring", "hinge", "stretch", "practice", "isolated"],
  ["man", "hamstring", "stretch", "elastic", "ring", "practice"],
  ["man", "handstand", "push", "up", "practice", "isolated"],
  ["man", "hanging", "knee", "leg", "raise", "abdominal", "practice", "isolated", "editable", "file", "layer", "mukta"],
  ["man", "hanging", "knee", "leg", "raise", "abdominal", "practice", "isolated", "editable", "file", "layer"],
  ["man", "hanging", "leg", "raise", "lat", "abdominal", "practice"],
  ["man", "hanging", "lat", "leg", "raise", "practice"],
  ["man", "high", "knee", "wall", "against", "wall", "practice"],
  ["man", "high", "knee", "forward", "knee", "lift", "run", "jog", "stance", "practice", "isolated"],
  ["man", "high", "knee", "forward", "knee", "lift", "run", "jog", "stance", "practice"],
  ["man", "high", "lunge", "forward", "twist", "hand", "folded", "back", "practice", "isolated"],
  ["man", "hip", "raise", "butt", "raise", "bridge", "curling", "shoulder", "bridge", "reach", "bodyweight", "practice", "isolated"],
  ["man", "incline", "bench", "opposite", "crunch", "practice"],
  ["man", "incline", "crunch", "punch", "practice"],
  ["man", "incline", "kettlebell", "bench", "press", "twist", "practice"],
  ["man", "viparita", "wall", "push", "up", "practice"],
  ["man", "isometric", "hip", "abduction", "ring", "resistance", "ring", "practice", "isolated", "mukta"],
  ["man", "jefferson", "squat", "practice", "bar"],
  ["man", "hop", "rope", "skipping", "cardio", "practice"],
  ["man", "hop", "squat", "practice", "isolated"],
  ["man", "jumping", "calf", "raise", "press", "practice", "isolated", "workout", "character", "setu"],
  ["man", "jumping", "jack", "star"],
  ["man", "jumping", "plyo", "jack", "star", "hop", "practice"],
  ["man", "kettle", "bell", "goblet", "squat", "practice", "isolated", "workout", "character", "setu"],
  ["man", "kettlebell", "deadlift", "ab", "practice", "isolated"],
  ["man", "kettlebell", "practice", "folded", "up", "rowing", "smash", "bell", "practice", "isolated", "workout", "character", "setu"],
  ["man", "kettlebell", "one", "legged", "deadlift", "practice", "isolated"],
  ["man", "kettlebell", "swing", "practice", "isolated"],
  ["man", "knee", "plank", "reach", "swimmer", "stand", "practice", "isolated"],
  ["man", "knee", "tuck", "hop", "practice", "isolated"],
  ["man", "kneeling", "cable", "crunch", "abdominal", "practice", "isolated"],
  ["man", "kneeling", "hip", "flexor", "stretch", "practice", "isolated"],
  ["man", "kneeling", "wrist", "forearm", "stretch", "isolated"],
  ["man", "knee", "chest", "stand", "apanasana", "practice", "isolated"],
  ["man", "krounchasana", "man", "yogi", "heron", "stand", "intense", "hamstring", "stretch", "boy", "leg", "up", "hand", "holding", "foot"],
  ["man", "landmine", "shoulder", "press", "practice", "isolated"],
  ["man", "lat", "raise", "home", "workout", "practice", "thin", "resistance", "ring", "guidance"],
  ["man", "lat", "raise", "resistance", "ring", "practice"],
  ["man", "lat", "lat", "shoulder", "kettlebell", "raise", "strength", "partial", "practice", "isolated", "mukta"],
  ["man", "lat", "stepping", "resistance", "ring", "practice", "isolated", "mukta"],
  ["man", "laying", "kettlebell", "internal", "shoulder", "rotation"],
  ["man", "laying", "internal", "shoulder", "rotation", "isolated"],
  ["man", "leaning", "one", "arm", "single", "handed", "kettlebell", "lat", "raise", "practice"],
  ["man", "leg", "press", "practice", "machine", "isolated", "mukta"],
  ["man", "leg", "stretch", "knee", "up", "isolated", "abdominal", "practice"],
  ["man", "raise", "lat", "hip", "abduction", "machine", "practice"],
  ["man", "long", "arm", "crunch", "practice", "isolated", "editable", "file", "layer", "mukta"],
  ["man", "low", "pulley", "tricep", "extension", "cable", "tricep", "kickback", "practice"],
  ["man", "low", "upward", "cable", "pulley", "crossover", "chest", "flye", "isolated"],
  ["man", "lunge", "twist", "practice", "isolated", "mukta"],
  ["man", "prone", "chest", "overhead", "extension", "practice", "isolated"],
  ["man", "prone", "forward", "down", "plate", "neck", "resistance", "practice", "isolated"],
  ["man", "prone", "leg", "curl", "practice", "isolated"],
  ["man", "prone", "leg", "raise", "practice", "abdominal", "practice", "body", "kettlebell", "lift", "mukta"],
  ["man", "prone", "lat", "leg", "lift", "lat", "raise", "hip", "abductor", "adductor", "leg", "raise", "practice", "ii", "step", "isolated"],
  ["man", "man", "twist", "practice", "abdominal", "excercise", "isolated"],
  ["man", "master", "tricep", "dip", "practice", "isolated", "workout", "character", "setu"],
  ["man", "med", "ball", "squat", "reach", "practice", "isolated"],
  ["man", "meditating", "sitting", "stretching", "neck", "lat", "liberation", "neck", "shoulder", "tension", "isolated"],
  ["man", "modified", "crunch", "abdominal", "practice"],
  ["man", "modified", "knee", "push", "up", "practice", "isolated", "workout", "character"],
  ["man", "modified", "plank", "shoulder", "tap"],
  ["man", "mountain", "climber", "practice", "isolated"],
  ["man", "mountain", "climber", "kettlebell", "practice", "isolated", "workout", "character", "setu"],
  ["man", "oblique", "crunch", "practice", "isolated", "mukta"],
  ["man", "oblique", "stretch", "practice", "isolated"],
  ["man", "one", "arm", "kettlebell", "snatch", "practice"],
  ["man", "one", "arm", "kettlebell", "row", "practice", "isolated", "mukta"],
  ["man", "one", "arm", "shoulder", "press", "kettlebell", "practice", "isolated"],
  ["man", "one", "handed", "kettlebell", "deadlift", "practice", "isolated", "workout", "character", "setu"],
  ["man", "one", "handed", "kettlebell", "deadlift", "practice", "isolated", "workout", "character", "setu"],
  ["man", "overhead", "cable", "curl", "crucifix", "curl", "isolated", "different", "layer", "workout", "character"],
  ["man", "overhead", "kettlebell", "shoulder", "press", "practice", "isolated", "mukta"],
  ["man", "overhead", "kettlebell", "shoulder", "press", "practice", "isolated"],
  ["man", "overhead", "pistol", "squat", "practice", "resistance", "ring"],
  ["man", "overhead", "plate", "press", "practice", "isolated", "mukta"],
  ["man", "overhead", "plate", "squat", "practice", "isolated", "mukta"],
  ["man", "overhead", "tricep", "extension", "practice", "kettlebell"],
  ["man", "overhead", "tricep", "stretch", "practice", "isolated", "mukta"],
  ["man", "overhead", "tricep", "stretch", "practice"],
  ["man", "perfect", "straddle", "plank", "push", "up", "bar"],
  ["man", "pigeon", "butt", "stretch", "practice"],
  ["man", "pike", "push", "up", "practice", "isolated"],
  ["man", "piriformi", "stretch", "practice", "isolated"],
  ["man", "pistol", "single", "leg", "long", "arm", "squat", "practice", "isolated"],
  ["man", "plank", "finger", "calisthenic", "practice"],
  ["man", "plank", "abdominal", "practice", "isolated", "mukta"],
  ["man", "plank", "abdominal", "practice", "isolated"],
  ["man", "plank", "up", "practice", "isolated", "mukta"],
  ["man", "plank", "roll", "practice", "abdominal", "practice", "isolated"],
  ["man", "plank", "push", "up", "movement", "stepping", "plank", "up", "down", "ab", "practice", "isolated"],
  ["man", "plank", "kettlebell", "abdominal", "practice"],
  ["man", "plate", "overhead", "stepping", "lunge", "practice", "isolated"],
  ["man", "strength", "lunge", "practice", "hop", "lunge"],
  ["man", "strength", "skip", "practice", "isolated"],
  ["man", "powerbag", "sandbag", "stepping", "lunge", "isolated"],
  ["man", "prone", "hamstring", "stretch", "laying", "hamstring", "stretch", "isolated"],
  ["man", "prone", "prone", "resistance", "ring", "knee", "bend", "practice"],
  ["man", "stretch", "up", "practice", "isolated", "mukta"],
  ["man", "push", "up", "isolated"],
  ["man", "push", "up", "one", "hand", "kettlebell", "practice", "isolated", "workout", "character", "setu"],
  ["man", "push", "up", "floor", "bar", "practice"],
  ["man", "quadricep", "stretch", "cooldown", "practice", "handstand", "stand", "flexibility", "improvement", "isolated"],
  ["man", "rack", "jerk", "practice", "isolated", "mukta"],
  ["man", "ragdoll", "forward", "twist", "tuck", "stretch", "practice", "isolated"],
  ["man", "raised", "one", "legged", "leg", "push", "up"],
  ["man", "back", "delt", "machine", "flye", "practice"],
  ["man", "back", "leg", "raise", "workout", "machine", "raise", "standing", "back", "kick", "practice"],
  ["man", "resistance", "ring", "bicep", "curl", "practice", "arm", "workout", "fitness", "man", "isolated"],
  ["man", "resistance", "ring", "calf", "stretch"],
  ["man", "resistance", "ring", "chest", "opener", "stretch", "practice"],
  ["man", "resistance", "ring", "deadlift", "practice", "isolated", "mukta"],
  ["man", "resistance", "ring", "dorsiflexion", "practice", "stretch", "ankle", "practice"],
  ["man", "resistance", "ring", "standing", "shoulder", "press", "overhead", "press", "practice", "isolated"],
  ["man", "resistance", "weighted", "crunch", "practice", "isolated", "workout", "character", "setu"],
  ["man", "opposite", "hand", "incline", "kettlebell", "bench", "press", "practice"],
  ["man", "opposite", "shoulder", "stretch", "practice", "isolated"],
  ["man", "rope", "bicep", "hammer", "curl", "isolated", "different", "layer", "workout", "character", "mukta"],
  ["man", "seal", "jack", "sport", "practice"],
  ["man", "sitting", "arnold", "press", "bench", "practice", "isolated"],
  ["man", "sitting", "kettlebell", "french", "press", "practice", "isolated", "mukta"],
  ["man", "sitting", "folded", "up", "back", "delt", "raise", "practice"],
  ["man", "sitting", "kettlebell", "bicep", "curl"],
  ["man", "sitting", "kettlebell", "hammer", "curl"],
  ["man", "sitting", "kettlebell", "lat", "raise", "strength", "partial", "practice", "isolated", "mukta"],
  ["man", "sitting", "kettlebell", "overhead", "shoulder", "press", "overhead", "body", "workout", "overhead", "body", "practice", "isolated"],
  ["man", "sitting", "kettlebell", "preacher", "bicep", "hammer", "curl", "practice"],
  ["man", "sitting", "self", "athlete", "back", "lotus", "stand", "paripurna", "lotus", "sitting", "stand", "yoga", "yoga", "breath", "holding", "sunken", "ab"],
  ["man", "sitting", "lat", "raise", "machine", "strength", "partial", "practice"],
  ["man", "sitting", "low", "cable", "back", "row", "practice", "isolated", "mukta"],
  ["man", "sitting", "low", "cable", "back", "row", "practice", "isolated", "mukta"],
  ["man", "sitting", "overhead", "kettlebell", "tricep", "extension"],
  ["man", "sitting", "overhead", "tricep", "press"],
  ["man", "sitting", "punch", "practice"],
  ["man", "sitting", "wide", "grup", "lat", "pulldown", "isolated", "mukta"],
  ["man", "sitting"],
  ["man", "lat", "curling", "mountain", "stand", "parsva", "tadasana", "practice", "isolated"],
  ["man", "lat", "bend", "stretching", "hand", "hip", "sport", "practice", "fitness", "workout", "isolated"],
  ["man", "lat", "lat", "leg", "hip", "swing", "practice"],
  ["man", "lat", "lat", "shuffle", "hop", "skater", "practice"],
  ["man", "lat", "plank", "abdominal", "practice", "isolated"],
  ["man", "lat", "lat", "hop", "squat", "practice"],
  ["man", "single", "arm", "folded", "up", "row", "practice", "isolated", "workout", "character", "setu", "mukta"],
  ["man", "single", "arm", "folded", "up", "row", "practice", "isolated", "workout", "character", "setu"],
  ["man", "single", "arm", "high", "push", "up", "kettlebell", "plate", "isolated"],
  ["man", "single", "arm", "floor", "butt", "bridge", "press", "practice", "isolated", "workout", "character", "setu"],
  ["man", "single", "leg", "kettlebell", "squat", "pistol", "squat", "practice", "isolated", "workout", "character", "setu"],
  ["man", "single", "leg", "butt", "bridge", "arm", "workout", "practice", "isolated"],
  ["man", "single", "leg", "squat", "pistol", "squat", "practice", "isolated"],
  ["man", "single", "leg", "squat", "pistol", "squat", "practice", "isolated", "workout", "character", "setu"],
  ["man", "single", "one", "arm", "kettlebell", "farmer", "stepping", "suitcase", "carry", "practice"],
  ["man", "single", "one", "arm", "forward", "water", "bottle", "raise", "practice"],
  ["man", "single", "one", "leg", "hop", "hop", "practice"],
  ["man", "sit", "up", "practice", "abdominal", "practice", "isolated"],
  ["man", "sled", "pushed", "practice", "isolated"],
  ["man", "smashbell", "training", "leg", "squat", "kettlebell", "practice", "isolated", "workout", "character", "setu"],
  ["man", "smashbell", "training", "leg", "squat", "kettlebell", "practice"],
  ["man", "snap", "hop", "practice"],
  ["man", "sphinx", "push", "up", "isolated"],
  ["man", "spider", "man", "press", "up", "practice", "isolated"],
  ["man", "split", "alternating", "squat", "hop", "practice"],
  ["man", "split", "jack", "practice"],
  ["man", "split", "squat", "hop", "practice", "isolated"],
  ["man", "sprinter", "crunch", "practice"],
  ["man", "squat", "jack", "lat", "sumo", "walk", "practice"],
  ["man", "squat", "tuck", "hop", "practice"],
  ["man", "squat", "kettlebell", "practice", "isolated", "mukta"],
  ["man", "squat", "lat", "leg", "raise", "leg", "lift", "practice"],
  ["man", "squat", "kettlebell", "neck", "back"],
  ["man", "balance", "swiss", "ball", "back", "extension", "practice"],
  ["man", "balance", "swiss", "ball", "hamstring", "leg", "curl", "hip", "raise", "bridge"],
  ["man", "balance", "swiss", "ball", "rollout", "practice", "man", "workout", "fitness"],
  ["man", "balance", "swiss", "ball", "wall", "squat", "practice"],
  ["man", "balance", "swiss", "ball", "crunch", "practice", "isolated"],
  ["man", "balance", "swiss", "ball", "push", "up", "practice", "isolated", "mukta"],
  ["man", "staggered", "hand", "push", "up", "practice"],
  ["man", "standing", "ab", "skater", "practice", "lat"],
  ["man", "standing", "arm", "ring", "practice", "isolated"],
  ["man", "standing", "bicep", "cable", "curl", "practice", "isolated", "different", "layer", "workout", "character"],
  ["man", "standing", "cable", "crossover", "press", "cable", "flye", "practice", "isolated", "workout", "character"],
  ["man", "standing", "calf", "raise", "assisted", "machine", "isolated"],
  ["man", "standing", "chair", "salamba", "hamstring", "curl", "practice"],
  ["man", "standing", "crucifix", "body", "arm", "shoulder", "stretch", "practice", "isolated"],
  ["man", "standing", "crucifix", "body", "arm", "shoulder", "stretch", "practice"],
  ["man", "standing", "kettlebell", "bicep", "curl", "isolated", "different", "layer", "training", "character"],
  ["man", "standing", "kettlebell", "bicep", "curl"],
  ["man", "standing", "kettlebell", "bicep", "hammer", "curl", "isolated", "different", "layer", "training", "character"],
  ["man", "standing", "kettlebell", "calf", "raise", "practice", "isolated", "workout", "character", "setu"],
  ["man", "standing", "kettlebell", "calf", "raise"],
  ["man", "standing", "kettlebell", "hammer", "curl", "isolated"],
  ["man", "standing", "hamstring", "stretch", "practice", "isolated"],
  ["man", "standing", "knee", "hug", "practice"],
  ["man", "standing", "quad", "stretch", "yoga", "workout", "wall", "isolated"],
  ["man", "standing", "reach", "up", "back", "rotation", "stretch", "practice"],
  ["man", "standing", "rope", "forward", "stretch", "cable", "forward", "stretch", "practice", "back", "shoulder", "exerciseflat", "isolated"],
  ["man", "standing", "spinal", "twist", "stand", "practice", "katichakrasana", "isolated"],
  ["man", "star", "crunch", "crunch", "abdominal", "practice"],
  ["man", "step", "up", "knee", "raise", "practice", "isolated"],
  ["man", "straight", "arm", "lat", "pulldown", "practice", "isolated", "mukta"],
  ["man", "straight", "arm", "pulldown", "practice", "isolated"],
  ["man", "straight", "bar", "low", "pulley", "cable", "curl", "isolated", "different", "layer", "workout", "character", "mukta"],
  ["man", "straight", "leg", "calf", "stretch", "practice", "isolated", "workout", "character", "setu"],
  ["man", "stretch", "practice", "four", "leg", "sit", "art", "floor"],
  ["man", "stretch", "lunge", "practice"],
  ["man", "sumo", "kettlebell", "deadlift", "practice", "isolated", "mukta"],
  ["man", "supta", "matsyendrasana", "supine", "spinal", "twist", "stand", "practice", "isolated"],
  ["man", "swiss", "ball", "bicep", "curl", "kettlebell"],
  ["man", "swiss", "ball", "leg", "lift", "practice", "body", "kettlebell", "lift", "mukta"],
  ["man", "swiss", "ball", "plank", "abdominal", "practice", "isolated", "mukta"],
  ["man", "swiss", "ball", "squeeze", "practice"],
  ["man", "squat", "push", "burpee", "stand", "step", "practice", "isolated"],
  ["man", "suitcase", "sit", "up", "practice"],
  ["man", "toe", "reach", "crunch", "practice", "man", "ab", "practice", "isolated"],
  ["man", "toe", "tap", "practice"],
  ["man", "trice", "dip", "practice"],
  ["man", "tricep", "kickback", "practice", "isolated"],
  ["man", "tricep", "kickback", "resistance", "ring", "practice"],
  ["man", "tricep", "kickback", "kettlebell"],
  ["man", "trx", "opposite", "lunge", "practice", "isolated"],
  ["man", "trx", "suspension", "strap", "saw", "pike", "practice", "isolated"],
  ["man", "trx", "suspension", "strap", "suspended", "lunge", "practice", "isolated"],
  ["man", "tuck", "hop", "cardio", "practice"],
  ["man", "tuck", "plank", "calisthenic", "practice", "parallette"],
  ["man", "turkish", "up", "practice", "isolated", "mukta"],
  ["man", "two", "arm", "kettlebell", "forward", "shoulder", "raise", "practice", "isolated", "mukta"],
  ["man", "two", "arm", "kettlebell", "swing", "practice", "isolated"],
  ["man", "upperbody", "rotation", "lunge", "kettlebell", "practice", "isolated", "workout", "character", "setu"],
  ["man", "standing", "kettlebell", "row", "practice"],
  ["man", "standing", "row", "home", "workout", "practice", "thin", "resistance", "ring", "isolated"],
  ["man", "volcano", "stand", "upward", "hand", "stand", "upward", "salute", "stand", "tadasana", "urdhva", "hastasana"],
  ["man", "stepping", "high", "kick", "martial", "march", "abdominal", "practice", "isolated"],
  ["man", "stepping", "lunge", "practice"],
  ["man", "wide", "legged", "sitting", "forward", "lean", "stretch", "practice", "practice", "agnistambhasana", "leaning", "forward"],
  ["man", "workout", "art", "office", "sitting", "chair", "spinal", "twist", "ardha", "matsyendrasana", "practice", "isolated"],
  ["man", "yoga", "cat", "cow", "stand", "stretch", "practice", "isolated"],
  ["man", "dynamic", "clap", "push", "up", "practice", "push", "up", "variation", "isolated", "workout", "character"],
  ["man", "hammer", "strength", "machine", "sitting", "chest", "press", "practice", "isolated", "workout", "character"],
  ["man", "kettlebell", "windmill", "practice", "isolated", "workout", "character", "setu"],
  ["man", "kneeling", "kettlebell", "press", "practice", "isolated", "workout", "character"],
  ["man", "bodybuilding", "kettlebell", "gym", "ez", "bar", "preacher", "curl", "making", "bicep", "practice", "isolated", "layer", "workout", "character"],
  ["man", "scarecrow", "arm", "elbow", "shoulder", "rotation", "kettlebell"],
  ["man", "stretching", "neck", "arm", "shoulder", "hand", "isolated"],
  ["man", "stretching", "thigh", "standing", "hamstring", "stretch", "isolated"],
  ["man", "stretching", "thigh", "leg", "workout", "isolated"],
  ["man", "strength", "abdominal", "ab", "prone", "single", "one", "leg", "lift", "raise", "isolated"],
  ["med", "ball", "alternating", "lat", "slam", "practice", "isolated", "workout", "character", "setu"],
  ["med", "ball", "floor", "press", "laying", "chest", "pass", "practice", "isolated", "chest", "practice"],
  ["med", "ball", "push", "up", "practice", "isolated", "chest", "practice"],
  ["med", "ball", "rotational", "pass", "practice", "isolated", "workout", "character", "setu"],
  ["med", "ball", "up", "practice", "isolated", "workout", "character", "setu"],
  ["mountain", "climber"],
  ["muscular", "adult", "man", "running", "jogging", "workout", "excercise", "marathon", "athlete", "sprint", "outdoor", "minimalistic"],
  ["muscular", "adult", "woman", "running", "jogging", "workout", "excercise", "marathon", "athlete", "sprint", "outdoor", "minimalistic"],
  ["not", "found"],
  ["plank", "shoulder", "tap", "practice", "isolated", "layered", "ab", "workout", "isolated"],
  ["plank", "shoulder", "tap", "practice", "isolated", "layered", "ab", "workout"],
  ["push", "up", "rotation"],
  ["quad", "stretch"],
  ["resistance", "ring", "chest", "press", "practice", "isolated", "chest", "workout"],
  ["opposite", "bench", "crunch", "practice", "isolated", "workout", "character", "setu"],
  ["opposite", "crunch", "practice", "isolated", "layered", "ab", "workout"],
  ["opposite", "plank", "kick", "practice", "isolated", "workout", "character", "setu"],
  ["russian", "mason", "sit", "twist", "practice", "isolated", "workout", "character", "setu"],
  ["russian", "twist", "kettlebell"],
  ["shoulder", "stretch"],
  ["lat", "lat", "med", "ball", "throw", "slam", "practice", "isolated", "workout", "character", "setu"],
  ["spiderman", "push", "up", "practice", "isolated"],
  ["squat", "kettlebell"],
  ["step", "up", "plyo", "boxing", "kettlebell"],
  ["athlete", "perform", "folded", "up", "row", "practice", "kettlebell", "minimalistic", "row", "style", "gym", "character", "setu"],
  ["tricep", "extension", "kettlebell"],
  ["tricep", "kickback", "kettlebell"],
  ["stepping", "lunge", "kettlebell"],
  ["woman", "degree", "curling", "hop", "squat", "sport", "practice", "woman", "practice", "workout", "training"],
  ["woman", "chest", "stretch", "practice", "isolated", "mukta"],
  ["woman", "wide", "squat", "sumo", "squat", "practice", "workout", "four", "glute", "hip"],
  ["woman", "shoulder", "press", "practice", "kettlebell", "machine", "practice", "isolated"],
  ["woman", "ab", "practice", "stand", "introduction", "plank", "knee", "elbow", "ii", "step", "four", "tutorial", "isolated"],
  ["woman", "accomplished", "siddhasana", "yoga", "practice"],
  ["woman", "advanced", "bridge", "practice", "isolated", "mukta"],
  ["woman", "advanced", "single", "leg", "bridge", "practice", "isolated", "mukta"],
  ["woman", "alternating", "kettlebell", "swing", "practice", "isolated", "mukta"],
  ["woman", "alternating", "leg", "raise", "clap", "practice"],
  ["woman", "alternating", "lunge", "forward", "raise", "practice", "mukta"],
  ["woman", "alternating", "plank", "row", "leg", "raise", "practice", "isolated", "mukta"],
  ["woman", "ankle", "ring", "practice", "isolated", "mukta"],
  ["woman", "ankle", "ring", "rotation", "roll", "practice", "isolated"],
  ["woman", "ankle", "hop", "practice", "isolated", "mukta"],
  ["woman", "ankle", "jumping", "jack", "practice"],
  ["woman", "ankle", "pumping", "practice", "ii", "step", "good", "practice", "stand", "relieve", "leg", "swelling", "safe", "back", "during", "pregnancy", "isolated"],
  ["woman", "ankle", "tap", "push", "up", "practice", "isolated", "mukta"],
  ["woman", "arm", "ring", "practice", "isolated", "mukta"],
  ["woman", "arm", "swing", "practice", "isolated", "mukta"],
  ["woman", "arm", "crucifix", "lat", "lunge", "practice", "isolated", "mukta"],
  ["woman", "arnold", "press", "practice", "isolated", "mukta"],
  ["woman", "asymmetrical", "push", "up", "practice", "isolated", "mukta"],
  ["woman", "stand", "romanian", "deadlift", "kettlebell", "four", "butt", "practice"],
  ["woman", "back", "extension", "practice", "bhujang", "raise"],
  ["woman", "backward", "butt", "raise", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "handstand", "chop", "practice", "isolated", "mukta"],
  ["woman", "balancing", "cow", "stand", "balancing", "bitilasana", "yoga", "practice"],
  ["woman", "banana", "stand", "bananasana", "practice"],
  ["woman", "banded", "walk", "practice"],
  ["woman", "kettlebell", "deadlift", "practice", "isolated", "mukta"],
  ["woman", "kettlebell", "deadlift", "practice", "isolated"],
  ["woman", "kettlebell", "forward", "raise", "practice", "isolated"],
  ["woman", "kettlebell", "kneeling", "squat", "setu", "isolated"],
  ["woman", "basketball", "shot", "practice", "isolated", "mukta"],
  ["woman", "battle", "rope", "folded", "wave", "practice"],
  ["woman", "battle", "rope", "jumping", "jack", "practice"],
  ["woman", "battle", "rope", "snake", "practice", "isolated", "backgroun"],
  ["woman", "bear", "hug", "snow", "angel", "stretch", "practice", "isolated", "mukta"],
  ["woman", "bear", "walk", "practice", "isolated", "mukta"],
  ["woman", "bellow", "breath", "bhastrika", "pranayama", "yoga", "practice"],
  ["woman", "bench", "tricep", "dip", "practice", "isolated"],
  ["woman", "folded", "up", "folded", "arm", "tricep", "kickback", "practice", "isolated"],
  ["woman", "folded", "up", "row", "press", "practice", "isolated", "mukta"],
  ["woman", "bicep", "curl", "practice", "isolated", "mukta"],
  ["woman", "bicep", "lat", "stretch", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "bicep", "stretch", "practice", "isolated", "mukta"],
  ["woman", "big", "arm", "ring", "practice", "isolated", "mukta", "ii"],
  ["woman", "big", "arm", "ring", "practice", "isolated", "mukta"],
  ["woman", "pigeon", "puppy", "alternating", "reach", "kickback", "practice", "isolated"],
  ["woman", "boat", "stand", "paripurna", "navasana", "practice", "mukta"],
  ["woman", "boat", "stand", "twist", "variation", "hand", "foot", "parivrtta", "navasana", "variation", "hand", "foot"],
  ["woman", "body", "kettlebell", "stepping", "lunge", "isolated"],
  ["woman", "bodyweight", "squat", "practice", "isolated", "mukta"],
  ["woman", "bodyweight", "squat", "practice", "isolated"],
  ["woman", "bodyweight", "squat", "up", "arm", "practice", "isolated"],
  ["woman", "bodyweight", "squat", "practice", "isolated"],
  ["woman", "butt", "squeeze", "practice", "isolated", "mukta"],
  ["woman", "bosu", "ball", "bridge", "hip", "raise", "butt", "bridge", "isolated"],
  ["woman", "bosu", "ball", "leg", "stretch", "knee", "tuck", "practice", "isolated"],
  ["woman", "bosu", "ball", "plank", "leg", "raise", "practice", "isolated"],
  ["woman", "bosu", "ball", "plank", "push", "up", "stepping", "plank", "up", "down", "practice", "isolated"],
  ["woman", "bosu", "ball", "squat", "practice", "isolated"],
  ["woman", "bosu", "ball", "static", "handstand", "practice", "isolated"],
  ["woman", "bound", "angel", "stand", "aerial", "baddha", "konasana", "aerial", "yoga", "practice"],
  ["woman", "bound", "lotus", "stand", "baddha", "padmasana"],
  ["woman", "bound", "lotus", "stand", "baddha", "padmasana", "yoga", "practice"],
  ["woman", "boxing", "breath", "stretch", "practice", "mukta"],
  ["woman", "boxer", "squat", "punch", "practice", "mukta"],
  ["woman", "breakdancer", "kick", "practice", "isolated", "mukta"],
  ["woman", "bridge", "twist", "practice", "isolated", "mukta"],
  ["woman", "bulgarian", "split", "squat", "practice", "isolated", "mukta"],
  ["woman", "bulgarian", "split", "squat", "practice", "isolated"],
  ["woman", "bunny", "hop", "stand", "handstand", "prep", "pike", "handstand", "stand", "yoga", "practice"],
  ["woman", "burpee", "push", "up", "practice", "isolated"],
  ["woman", "butterfly", "stretch", "practice", "mukta"],
  ["woman", "cable", "hammer", "bicep", "curl", "practice", "arm", "workout", "fitness", "man", "isolated"],
  ["woman", "cable", "stretch", "practice", "isolated"],
  ["woman", "cable", "squat", "row", "practice", "isolated", "backgound", "row", "squat"],
  ["woman", "cable", "tricep", "kickback", "practice", "isolated"],
  ["woman", "cable", "standing", "row", "practice", "isolated"],
  ["woman", "calf", "stretching", "stand", "ankle", "isolated"],
  ["woman", "cat", "tail", "pulling", "stand", "cat", "tail", "pulling", "stand"],
  ["woman", "chair", "spinal", "twist", "ardha", "matsyendrasana", "practice", "isolated", "mukta"],
  ["woman", "chair", "squat", "practice", "partial", "ardha", "squat", "chair", "four", "athlete"],
  ["woman", "chest", "crossover", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "chest", "flye", "practice", "isolated", "mukta"],
  ["woman", "chest", "flye", "butt", "bridge", "practice", "isolated", "mukta"],
  ["woman", "child", "stand", "stretch", "practice", "mukta"],
  ["woman", "chin", "stand", "ganda", "bherundasana", "yoga", "practice"],
  ["woman", "chin", "up", "assistance", "resistance", "ring", "practice"],
  ["woman", "chin", "up", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "ring", "sky", "practice", "isolated", "mukta"],
  ["woman", "bhujang", "ab", "stretch", "old", "horse", "stretch", "abdominal", "practice", "isolated", "editable", "file", "layer", "mukta"],
  ["woman", "bhujang", "lat", "pulldown", "practice", "isolated", "mukta"],
  ["woman", "bhujang", "stand", "bhujangasana", "practice", "mukta"],
  ["woman", "cock", "stand", "rooster", "stand", "kukkutasana"],
  ["woman", "compass", "stand", "sundial", "stand", "surya", "yantrasana", "yoga", "practice"],
  ["woman", "concentration", "curl", "practice", "isolated", "mukta"],
  ["woman", "ab", "control", "back", "lunge", "practice", "isolated", "mukta"],
  ["woman", "ab", "sitting", "ab", "twist", "resistance", "ring", "practice", "isolated"],
  ["woman", "ab", "lat", "bend", "resistance", "ring", "practice", "isolated"],
  ["woman", "cossack", "squat", "practice"],
  ["woman", "crab", "kick", "practice", "isolated", "mukta"],
  ["woman", "crescent", "low", "lunge", "stand", "variation", "hand", "toe", "anjaneyasana", "variation", "hand", "toe"],
  ["woman", "crucifix", "body", "mountain", "climber", "practice", "isolated", "mukta"],
  ["woman", "crucifix", "jack", "practice", "mukta"],
  ["woman", "crow", "stand", "eagle", "leg", "bakasana", "pada", "garudasana"],
  ["woman", "crunch", "chop", "practice", "isolated", "mukta"],
  ["woman", "crunch", "isolated"],
  ["woman", "curtsy", "lunge", "lat", "kick", "lat", "raise", "practice", "mukta"],
  ["woman", "dead", "bug", "practice", "abdominal", "practice", "isolated", "editable", "file", "layer"],
  ["woman", "decline", "push", "up", "practice", "isolated", "mukta"],
  ["woman", "decline", "push", "up", "practice", "isolated"],
  ["woman", "diamond", "pyramid", "push", "up", "practice", "isolated"],
  ["woman", "donkey", "kick", "kicking", "plank", "practice"],
  ["woman", "folded", "leg", "stretch", "resistance", "ring", "practice", "isolated"],
  ["woman", "folded", "pulse", "squat", "hop", "practice", "isolated", "mukta"],
  ["woman", "down", "puppy", "ab", "practice", "isolated"],
  ["woman", "adho", "facing", "puppy", "split", "stand", "down", "puppy", "split", "eka", "pada", "adho", "mukha", "svanasana"],
  ["woman", "kettlebell", "folded", "up", "chest", "salamba", "opposite", "flye"],
  ["woman", "kettlebell", "folded", "up", "lat", "back", "delt", "raise", "flye", "practice", "isolated"],
  ["woman", "kettlebell", "folded", "up", "lat", "back", "delt", "raise", "flye", "practice", "isolated"],
  ["woman", "kettlebell", "folded", "up", "row", "practice", "isolated", "mukta"],
  ["woman", "kettlebell", "bicep", "curl", "isolated", "different", "layer", "workout", "character", "mukta"],
  ["woman", "kettlebell", "bicep", "hammer", "curl", "isolated", "different", "layer", "workout", "character", "mukta"],
  ["woman", "kettlebell", "bicep", "hammer", "curl", "isolated", "different", "layer", "workout", "character", "mukta"],
  ["woman", "kettlebell", "chest", "press", "practice", "isolated", "mukta"],
  ["woman", "kettlebell", "lunge", "setu", "workout", "icon", "style", "isolated", "mukta"],
  ["woman", "kettlebell", "overhead", "shoulder", "press", "practice", "isolated", "mukta"],
  ["woman", "kettlebell", "pullover", "leg", "raise", "practice", "isolated", "mukta"],
  ["woman", "kettlebell", "shrug", "practice", "isolated"],
  ["woman", "kettlebell", "step", "up", "practice", "isolated"],
  ["woman", "kettlebell", "thruster", "squat", "overhead", "press", "practice", "mukta"],
  ["woman", "kettlebell", "tricep", "extension", "practice", "isolated", "mukta"],
  ["woman", "laghu", "lat", "reclining", "stand", "variation", "sahaja", "anantasana", "variation"],
  ["woman", "eight", "legged", "stand", "bound", "hand", "ashtangasana", "baddha", "hasta", "yoga", "practice"],
  ["woman", "eight", "legged", "yoga", "stand", "ashtangasana", "practice", "isolated"],
  ["woman", "high", "kettlebell", "flute", "bridge", "hip", "raise", "practice", "isolated"],
  ["woman", "high", "boat", "stand", "utthita", "navasana", "yoga", "practice"],
  ["woman", "embryo", "pindasana", "yoga", "practice"],
  ["woman", "embryo", "stand", "embryo", "embryo", "stand", "garbhasana", "garbha", "pindasana", "yoga", "practice"],
  ["woman", "practice", "isolated", "mukta"],
  ["woman", "practice", "opposite", "lunge", "stand", "water", "bottle"],
  ["woman", "practice", "single", "leg", "hip", "rotation", "stand", "hip", "leg"],
  ["woman", "practice", "pilate", "reformer"],
  ["woman", "explosive", "butt", "kick", "practice"],
  ["woman", "explosive", "jumping", "alternating", "lunge", "practice", "step", "four", "lower", "body", "hamstring", "isolated"],
  ["woman", "long", "mountain", "stand", "backbend", "interlocked", "hand", "utthita", "tadasana", "backbend", "baddhanguliyasana"],
  ["woman", "long", "puppy", "yoga", "stand", "uttana", "shishosana"],
  ["woman", "external", "cable", "shoulder", "rotation", "stand", "four", "practice", "ii", "step", "workout", "gym", "equipment", "maintain", "strong", "stable", "shoulder", "knee"],
  ["woman", "external", "rotation", "bodyweight", "calf", "raise", "practice", "isolated"],
  ["woman", "fallen", "angel", "stand", "devaduuta", "panna", "yoga", "yoga", "practice"],
  ["woman", "character", "squat", "practice", "mukta"],
  ["woman", "character", "skater", "stand", "pada", "vakra", "trikonasana", "yoga", "practice"],
  ["woman", "fingertip", "toe", "jack", "practice", "mukta"],
  ["woman", "five", "pointed", "star", "stand", "viparita", "aerial", "utthita", "tadasana", "viparita", "aerial", "yoga", "practice"],
  ["woman", "floor", "strength", "hop", "knee", "hop", "squat", "practice", "isolated"],
  ["woman", "floor", "raise", "practice", "isolated"],
  ["woman", "butterfly", "kick", "squat", "practice", "isolated", "mukta"],
  ["woman", "butterfly", "kick", "practice", "isolated"],
  ["woman", "foam", "skater", "calf", "calf", "stretch", "practice", "isolated"],
  ["woman", "foam", "skater", "inner", "thigh", "adductor", "adduction", "stretch", "practice", "isolated"],
  ["woman", "foam", "skater", "lat", "stretch", "practice"],
  ["woman", "foam", "skater", "neck", "liberation", "practice"],
  ["woman", "foam", "skater", "quadricep", "stretch", "practice", "isolated"],
  ["woman", "foam", "skater", "overhead", "back", "stretch", "practice", "isolated"],
  ["woman", "foot", "behind", "head", "stand", "eka", "pada", "sirsasana", "yoga", "practice"],
  ["woman", "forearm", "plank", "practice", "isolated"],
  ["woman", "forearm", "lat", "plank", "stand", "arm", "down", "forearm", "vasisthasana", "arm", "down"],
  ["woman", "forward", "forward", "shoulder", "single", "kettlebell", "raise", "practice", "isolated", "mukta"],
  ["woman", "forward", "forward", "shoulder", "single", "kettlebell", "raise", "practice", "isolated", "mukta"],
  ["woman", "forward", "hop", "shuffle", "back", "practice", "mukta"],
  ["woman", "forward", "leg", "hip", "swing", "practice", "isolated"],
  ["woman", "forward", "leg", "swing", "holding", "wall", "practice", "isolated", "mukta"],
  ["woman", "frog", "bridge", "practice", "isolated", "mukta"],
  ["woman", "frog", "bhujang", "stand", "bheka", "bhujangasana", "yoga", "practice"],
  ["woman", "frog", "hop", "practice", "mukta"],
  ["woman", "forward", "raise", "bar", "calisthenic", "practice"],
  ["woman", "forward", "raise", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "paripurna", "spinal", "twist", "stand", "sitting", "spinal", "twist", "poorna", "matsyendrasana"],
  ["woman", "garland", "stand", "malasana", "practice", "isolated", "mukta"],
  ["woman", "gate", "swing", "practice", "isolated", "mukta"],
  ["woman", "gluteus", "butt", "stretch", "practice", "isolated"],
  ["woman", "goblet", "squat", "practice", "isolated", "mukta"],
  ["woman", "grappling", "reach", "back", "practice", "isolated", "mukta"],
  ["woman", "gymnastic", "ring", "grip", "practice", "isolated"],
  ["woman", "ardha", "bound", "angel", "stand", "viparita", "aerial", "ardha", "baddha", "konasana", "viparita", "aerial"],
  ["woman", "ardha", "bound", "lotus", "boat", "stand", "ardha", "baddha", "padma", "navasana", "yoga", "practice"],
  ["woman", "ardha", "bridge", "practice", "isolated"],
  ["woman", "ardha", "camel", "stand", "variation", "raised", "toe", "ardha", "ustrasana", "variation", "raised", "toe", "yoga", "practice"],
  ["woman", "ardha", "lord", "fish", "ardha", "matsyendrasana", "practice", "isolated", "mukta"],
  ["woman", "ardha", "lotus", "laghu", "fish", "stand", "variation", "beautiful", "girl", "practice", "matsyasana", "variation", "padmasana", "elbow", "isolated"],
  ["woman", "ardha", "modified", "one", "leg", "push", "up", "practice", "isolated"],
  ["woman", "ardha", "split", "stand", "ardha", "monkey", "stand", "ardha", "hanumanasana"],
  ["woman", "ardha", "static", "kettlebell", "bicep", "curl", "practice"],
  ["woman", "hammer", "hand", "curl", "long", "resistance", "ring", "practice", "isolated", "mukta"],
  ["woman", "hamstring", "leg", "curl", "practice", "mukta"],
  ["woman", "hamstring", "stretch", "four", "practice", "isolated"],
  ["woman", "hamstring", "stretch", "practice", "isolated"],
  ["woman", "hamstring", "stretch", "practice", "mukta"],
  ["woman", "hamstring", "stretch", "elastic", "ring", "practice", "isolated"],
  ["woman", "handstand", "stand", "aerial", "adho", "mukha", "vrksasana", "aerial", "yoga", "practice"],
  ["woman", "handstand", "stand", "prep", "aerial", "adho", "mukha", "vrksasana", "prep", "aerial", "yoga", "practice"],
  ["woman", "happy", "baby", "stand", "practice", "isolated", "mukta"],
  ["woman", "head", "knee", "forward", "twist", "stand", "kanu", "sirsasana", "practice", "isolated", "mukta"],
  ["woman", "headstand", "stand", "bound", "angel", "leg", "salamba", "sirsasana", "baddha", "konasana", "yoga", "practice"],
  ["woman", "headstand", "stand", "eagle", "leg", "salamba", "sirsasana", "pada", "garudasana"],
  ["woman", "heisman", "shuffle", "lat", "lat", "ice", "skater", "hop", "practice", "mukta"],
  ["woman", "hex", "trap", "bar", "cage", "deadlift", "squat", "practice", "isolated", "mukta"],
  ["woman", "high", "boxing", "hop", "practice", "isolated"],
  ["woman", "high", "kick", "practice", "mukta"],
  ["woman", "high", "knee", "forward", "knee", "lift", "run", "jog", "stance", "practice", "isolated", "mukta"],
  ["woman", "high", "lunge", "quad", "stretch", "alanasan", "practice", "ashta", "chandrasana", "isolated"],
  ["woman", "hip", "ring", "practice", "isolated"],
  ["woman", "hip", "ring", "stand", "aerial", "hip", "circel", "stand", "aerial", "yoga", "practice"],
  ["woman", "hip", "flexor", "stretch", "practice"],
  ["woman", "hip", "raise", "butt", "raise", "bridge", "practice", "isolated"],
  ["woman", "humble", "flamingo", "stand", "humble", "flamingo", "stand", "yoga", "practice"],
  ["woman", "jack", "practice", "isolated", "mukta"],
  ["woman", "inchworm", "practice", "isolated", "mukta"],
  ["woman", "incline", "plank", "shoulder", "tap", "practice", "isolated", "layered", "ab", "workout"],
  ["woman", "incline", "push", "up", "practice", "isolated"],
  ["woman", "inner", "thigh", "lift", "practice", "mukta"],
  ["woman", "viparita", "row", "practice", "isolated"],
  ["woman", "lunge", "crucifix", "practice", "kettlebell"],
  ["woman", "hop", "back", "hop", "yoga", "practice"],
  ["woman", "hop", "rope", "skipping", "cardio", "practice", "isolated", "mukta"],
  ["woman", "hop", "rope", "skipping", "cardio", "practice"],
  ["woman", "hop", "squat", "practice", "isolated", "mukta"],
  ["woman", "hop", "squat", "practice", "isolated"],
  ["woman", "hop", "start", "practice", "mukta"],
  ["woman", "jumping", "calf", "press", "raise", "practice", "isolated"],
  ["woman", "kasyapasana", "lat", "plank", "bound", "ardha", "lotus", "practice", "isolated"],
  ["woman", "kettlebell", "deadlift", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "kettlebell", "goblet", "squat", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "kettlebell", "goblet", "squat", "practice"],
  ["woman", "kettlebell", "lunge", "press", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "kettlebell", "one", "legged", "deadlift", "practice", "isolated", "mukta"],
  ["woman", "kettlebell", "russian", "twist", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "kettlebell", "windmill", "practice"],
  ["woman", "king", "dancer", "stand", "aerial", "baddha", "natarajasana", "aerial"],
  ["woman", "knee", "elbow", "press", "up", "practice", "isolated", "mukta"],
  ["woman", "knee", "ring", "practice", "mukta"],
  ["woman", "knee", "plank", "practice", "isolated"],
  ["woman", "knee", "plank", "reach", "swimmer", "stand", "practice", "isolated"],
  ["woman", "knee", "push", "up", "practice", "isolated"],
  ["woman", "knee", "chest", "lower", "back", "stretch", "practice", "isolated"],
  ["woman", "knee", "chest", "spinal", "twist", "stretch", "practice", "isolated", "mukta"],
  ["woman", "knee", "squat"],
  ["woman", "knee", "tuck", "hop", "practice"],
  ["woman", "kneeling", "hip", "flexor", "stretch", "practice", "isolated"],
  ["woman", "kneeling", "roundhouse", "kick", "practice", "isolated", "mukta"],
  ["woman", "kneeling", "wrist", "forearm", "stretch", "isolated"],
  ["woman", "knee", "chest", "chin", "stand", "ashtanga", "namaskar", "practice", "isolated", "mukta"],
  ["woman", "lat", "ring", "stepping", "practice", "isolated", "mukta"],
  ["woman", "lat", "leg", "swing", "practice", "isolated", "mukta"],
  ["woman", "lat", "raise", "resistance", "ring", "practice", "isolated"],
  ["woman", "lat", "lat", "shoulder", "kettlebell", "raise", "strength", "partial", "practice"],
  ["woman", "lat", "step", "jerk", "practice", "isolated", "mukta"],
  ["woman", "laying", "external", "shoulder", "rotation"],
  ["woman", "laying", "internal", "shoulder", "rotation", "isolated"],
  ["woman", "leg", "loop", "practice", "isolated", "mukta"],
  ["woman", "leg", "raise", "reach", "clap", "practice"],
  ["woman", "leg", "up", "wall", "stand", "viparita", "karani", "stretch", "practice", "isolated", "mukta"],
  ["woman", "small", "thunderbolt", "stand", "laghu", "vajrasana", "yoga", "practice"],
  ["woman", "lizard", "stand", "utthan", "pristhasana", "practice", "isolated", "mukta"],
  ["woman", "lizard", "stand", "variation", "holding", "back", "foot", "utthan", "pristhasana", "variation", "holding", "back", "foot"],
  ["woman", "low", "lunge", "quad", "stretch", "stand", "anjaneyasana", "practice", "isolated", "mukta"],
  ["woman", "low", "plank", "stand", "chaturanga", "dandasana", "practice", "isolated", "mukta"],
  ["woman", "lunge", "back", "kick", "practice", "isolated", "mukta"],
  ["woman", "lunge", "forward", "kick", "practice", "isolated"],
  ["woman", "lunge", "punch", "kettlebell", "practice", "isolated", "mukta"],
  ["woman", "lunge", "step", "up", "practice", "workout", "four", "glute", "hip"],
  ["woman", "lunge", "twist", "practice", "isolated", "mukta"],
  ["woman", "lunge", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "lunge", "lunge", "punch", "practice", "isolated"],
  ["woman", "prone", "kettlebell", "tricep", "extension", "practice", "isolated"],
  ["woman", "prone", "leg", "curl", "practice"],
  ["woman", "prone", "leg", "raise", "lift", "practice", "isolated"],
  ["woman", "prone", "lat", "hip", "abduction", "practice", "isolated"],
  ["woman", "prone", "lat", "leg", "lift", "lat", "raise", "hip", "abductor", "adductor", "leg", "raise", "practice", "ii", "step", "isolated"],
  ["woman", "march", "stance", "practice", "mukta"],
  ["woman", "med", "ball", "chest", "step", "practice", "isolated"],
  ["woman", "med", "ball", "deadlift", "practice", "isolated"],
  ["woman", "med", "ball", "floor", "press", "laying", "chest", "pass", "practice", "isolated"],
  ["woman", "med", "ball", "squat", "practice", "isolated"],
  ["woman", "med", "ball", "swing", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "med", "ball", "up", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "med", "ball", "wall", "sit", "rotation", "practice", "mukta"],
  ["woman", "med", "ball", "wood", "chop", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "med", "ball", "wood", "chop", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "meditating", "sitting", "stretching", "neck", "lat", "liberation", "neck", "shoulder", "tension", "isolated"],
  ["woman", "modified", "crunch", "abdominal", "practice"],
  ["woman", "modified", "crunch", "abdominal", "practice"],
  ["woman", "modified", "jumping", "jack", "practice", "mukta"],
  ["woman", "modified", "knee", "push", "up", "practice", "isolated", "workout", "character", "mukta"],
  ["woman", "modified", "plank", "shoulder", "tap"],
  ["woman", "modified", "lat", "plank", "knee", "down", "practice", "isolated"],
  ["woman", "mountain", "climber", "twist", "practice", "isolated", "mukta"],
  ["woman", "neck", "massage", "ball", "practice", "isolated", "mukta"],
  ["woman", "neck", "stretch", "practice", "isolated"],
  ["woman", "oblique", "crunch", "practice", "isolated", "mukta"],
  ["woman", "oblique", "stretch", "practice", "isolated", "mukta"],
  ["woman", "one", "arm", "kettlebell", "row", "practice", "isolated"],
  ["woman", "one", "arm", "tricep", "kickback", "practice", "isolated", "mukta"],
  ["woman", "one", "legged", "handstand", "stand", "prep", "aerial", "eka", "pada", "adho", "mukha", "vrksasana", "yoga", "practice"],
  ["woman", "one", "legged", "plank", "stand", "bow", "leg", "eka", "pada", "phalakasana", "dhanura", "pada"],
  ["woman", "overhead", "cable", "curl", "crucifix", "curl", "isolated", "different", "layer", "workout", "character"],
  ["woman", "overhead", "kettlebell", "shoulder", "press", "practice", "isolated", "mukta"],
  ["woman", "overhead", "press", "resistance", "ring", "practice", "isolated"],
  ["woman", "palloff", "press", "oblique", "iso", "grip", "practice"],
  ["woman", "hand", "tree", "stand", "prep", "urdhva", "hastasana", "prep"],
  ["woman", "paschimottanasana", "sitting", "forward", "twist", "practice", "isolated", "mukta"],
  ["woman", "pawanmuktasana", "wind", "liberation", "stand", "practice", "isolated"],
  ["woman", "peacock", "stand", "practice", "mayurasana", "yoga", "practice"],
  ["woman", "during", "stand", "block", "lolasana", "block", "yoga", "practice"],
  ["woman", "perfect", "straddle", "plank", "push", "up", "bar"],
  ["woman", "pigeon", "butt", "stretch", "practice", "isolated", "mukta"],
  ["woman", "pigeon", "stand", "kapotasana", "yoga", "practice"],
  ["woman", "pigeon", "stand", "practice", "kapotasana", "yoga", "practice"],
  ["woman", "pilate", "hundred", "practice", "isolated", "mukta"],
  ["woman", "pilate", "workout", "reformer", "machine"],
  ["woman", "plank", "row", "renegade", "row", "practice", "isolated"],
  ["woman", "plank", "hip", "dip", "practice", "isolated", "mukta"],
  ["woman", "plank", "jack", "long", "leg", "practice", "isolated"],
  ["woman", "plank", "leg", "lift", "practice", "isolated", "mukta"],
  ["woman", "plank", "stand", "phalakasana", "practice", "isolated", "mukta"],
  ["woman", "plank", "toe", "tap", "practice", "isolated", "mukta"],
  ["woman", "plie", "squat", "calf", "raise", "practice", "isolated", "mukta"],
  ["woman", "plie", "squat", "scoop", "up", "practice", "isolated", "mukta"],
  ["woman", "strength", "bag", "sandbag", "good", "morning", "practice", "four", "backside", "workout", "isolated"],
  ["woman", "strength", "skip", "practice", "isolated"],
  ["woman", "powerbag", "sandbag", "stepping", "lunge", "isolated"],
  ["woman", "prisoner", "up", "practice", "kettlebell", "four", "quad"],
  ["woman", "prone", "back", "extension", "practice", "isolated"],
  ["woman", "prone", "hamstring", "stretch", "laying", "hamstring", "stretch", "isolated"],
  ["woman", "prone", "leg", "curl", "practice"],
  ["woman", "prone", "prone", "knee", "bend", "practice"],
  ["woman", "prone", "prone", "leg", "lift", "practice", "isolated"],
  ["woman", "prone", "prone", "resistance", "ring", "knee", "bend", "practice"],
  ["woman", "stretch", "up", "practice", "machine", "assisted", "stretch", "up"],
  ["woman", "stretch", "up", "kettlebell", "vest"],
  ["woman", "pulse", "up", "practice", "isolated", "mukta"],
  ["woman", "quick", "foot", "practice", "mukta"],
  ["woman", "ragdoll", "forward", "twist", "tuck", "stretch", "practice"],
  ["woman", "raised", "arm", "stand", "raised", "hand", "stand", "hasta", "uttanasana"],
  ["woman", "raised", "one", "legged", "leg", "push", "up", "practice"],
  ["woman", "back", "delt", "machine", "flye", "practice"],
  ["woman", "back", "leg", "raise", "resistance", "ring", "practice", "isolated", "mukta"],
  ["woman", "supta", "bound", "lotus", "stand", "supta", "baddha", "padmasana", "yoga", "practice"],
  ["woman", "reclining", "superman", "stand", "saddle", "stand", "supta", "virasana"],
  ["woman", "reclining", "turtle", "stand", "sleeping", "tortoise", "stand", "supta", "kurmasana"],
  ["woman", "renegade", "row", "adho", "puppy", "tap", "plank", "adho", "puppy", "practice", "isolated"],
  ["woman", "resistance", "ring", "chest", "opener", "stretch", "practice"],
  ["woman", "resistance", "ring", "crab", "stepping", "practice"],
  ["woman", "resistance", "ring", "dorsiflexion", "practice", "stretch", "ankle", "practice"],
  ["woman", "resistance", "ring", "knee", "raise", "standing", "knee", "raise", "ab", "practice"],
  ["woman", "resistance", "ring", "squat", "leg", "abduction", "practice", "mukta"],
  ["woman", "resistance", "weighted", "crunch", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "opposite", "lunge", "med", "ball", "overhead", "press", "practice", "mukta"],
  ["woman", "opposite", "lunge", "shoulder", "press", "practice", "mukta"],
  ["woman", "opposite", "pigeon", "stand", "sucirandhrasana"],
  ["woman", "opposite", "shoulder", "stretch", "practice", "isolated"],
  ["woman", "opposite", "table", "overhead", "stand", "leg", "character", "four", "ardha", "purvottanasana", "pada", "ardha", "utkatasana"],
  ["woman", "opposite", "table", "overhead", "stand", "leg", "character", "four", "ardha", "purvottanasana", "pada", "ardha", "utkatasana", "ii"],
  ["woman", "opposite", "table", "overhead", "stand", "leg", "character", "four", "ardha", "purvottanasana", "pada", "ardha", "utkatasana"],
  ["woman", "opposite", "table", "overhead", "stand", "leg", "character", "four", "ardha", "purvottanasana", "pada", "ardha", "utkatasana"],
  ["woman", "revolved", "head", "knee", "prep", "parivrtta", "janu", "sirsasana", "prep"],
  ["woman", "revolved", "thunderbolt", "stand", "parivrtta", "vajrasana"],
  ["woman", "revolved", "wide", "angel", "forward", "twist", "parivrtta", "prasarita", "padottanasana"],
  ["woman", "rising", "standing", "bhujang", "stand", "utthita", "stiti", "bhujangasana", "yoga", "practice"],
  ["woman", "rolling", "ball", "practice", "isolated", "mukta"],
  ["woman", "run", "stance", "practice", "mukta"],
  ["woman", "russian", "twist", "practice", "isolated", "mukta"],
  ["woman", "russian", "twist", "mason", "sit", "twist", "practice"],
  ["woman", "sage", "marichi", "stand", "variation", "beautiful", "girl", "practice", "marichyasana", "variation", "isolated"],
  ["woman", "salamba", "bhujangasana", "sphinx", "stand", "practice", "isolated", "mukta"],
  ["woman", "scissor", "kick", "practice", "isolated", "mukta"],
  ["woman", "scissor", "skier", "practice", "isolated", "mukta"],
  ["woman", "scorpion", "stretch"],
  ["woman", "seal", "jack", "sport", "practice"],
  ["woman", "sitting", "arnold", "press", "bench", "practice"],
  ["woman", "sitting", "kettlebell", "french", "press", "practice", "isolated"],
  ["woman", "sitting", "kettlebell", "martial", "press", "practice", "shoulder", "overhead", "press"],
  ["woman", "sitting", "bench", "long", "butterfly", "kick", "practice"],
  ["woman", "sitting", "bench", "leg", "stretch", "bench", "knee", "up", "practice", "isolated", "mukta"],
  ["woman", "sitting", "kettlebell", "concentration", "curl", "practice", "isolated", "mukta"],
  ["woman", "sitting", "kettlebell", "lat", "raise", "strength", "partial", "practice", "isolated", "mukta"],
  ["woman", "sitting", "kettlebell", "chair", "calf", "raise", "keep", "leg", "art", "degree", "angel", "stretch", "heel", "pushing", "toe", "floor", "bodybuilding", "heel", "pushing"],
  ["woman", "sitting", "forward", "stretch", "back", "delt", "stretch", "practice"],
  ["woman", "sitting", "self", "athlete", "back", "lotus", "stand", "paripurna", "lotus", "sitting", "stand", "yoga", "yoga", "breath", "holding", "sunken", "ab"],
  ["woman", "sitting", "lat", "lat", "shoulder", "kettlebell", "raise", "practice", "isolated", "mukta"],
  ["woman", "sitting", "leg", "curl", "practice", "isolated", "mukta"],
  ["woman", "sitting", "machine", "leg", "extension", "practice"],
  ["woman", "sitting", "single", "arm", "overhead", "kettlebell", "tricep", "extension", "practice", "isolated", "mukta"],
  ["woman", "sitting", "toe", "tap", "stretch", "practice", "isolated"],
  ["woman", "shoulder", "pole", "broomstick", "stretch", "practice"],
  ["woman", "shoulder", "squeeze", "opposite", "lunge", "practice", "mukta"],
  ["woman", "shoulder", "stretch", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "shoulderstand", "seal", "stand", "salamba", "shoulderstand", "yoga", "mudrasana"],
  ["woman", "shrimp", "squat", "practice", "mukta"],
  ["woman", "lat", "crow", "stand", "lat", "crane", "stand", "parsva", "bakasana", "parsva", "kakasana"],
  ["woman", "lat", "crunch", "leg", "raise", "practice", "isolated", "mukta"],
  ["woman", "lat", "lat", "leg", "hip", "swing", "practice"],
  ["woman", "lat", "leg", "lift", "practice", "isolated"],
  ["woman", "lat", "leg", "lift", "inner", "thigh", "squeeze", "practice", "mukta"],
  ["woman", "lat", "lunge", "curl", "practice", "mukta"],
  ["woman", "lat", "lunge", "forward", "raise", "practice", "mukta"],
  ["woman", "lat", "lunge", "curtsy", "lunge", "practice", "isolated", "mukta"],
  ["woman", "lat", "prone", "quad", "stretch", "practice", "isolated"],
  ["woman", "lat", "lat", "shuffle", "hop", "skater", "practice"],
  ["woman", "lat", "plank", "crunch", "practice", "isolated"],
  ["woman", "lat", "plank", "practice", "isolated", "mukta"],
  ["woman", "lat", "plank", "forward", "kick", "practice", "isolated", "mukta"],
  ["woman", "lat", "plank", "stand", "sage", "vasistha", "stand", "beautiful", "girl", "practice", "vasisthasana", "practice", "isolated"],
  ["woman", "lat", "plank", "stand", "vasisthasana", "practice", "isolated", "mukta"],
  ["woman", "lat", "plank", "rotation", "practice", "isolated", "mukta"],
  ["woman", "lat", "plank", "rotation", "elbow", "twist", "practice"],
  ["woman", "lat", "plank", "twist", "arm", "overhead", "vasisthasana", "twist", "arm", "overhead"],
  ["woman", "lat", "plank", "variation", "revolved", "ardha", "bound", "stand", "vasisthasana", "variation", "parivrtta", "ardha", "baddha", "yoga"],
  ["woman", "lat", "shuffle", "practice", "isolated", "mukta"],
  ["woman", "lat", "lat", "hop", "practice", "mukta"],
  ["woman", "lat", "lat", "hop", "squat", "practice"],
  ["woman", "lat", "lat", "squat", "practice", "mukta"],
  ["woman", "single", "arm", "folded", "up", "row", "practice", "isolated", "workout", "character", "setu", "mukta"],
  ["woman", "single", "arm", "kettlebell", "overhead", "shoulder", "press", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "single", "arm", "floor", "butt", "bridge", "press", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "single", "arm", "med", "ball", "push", "up", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "single", "leg", "bridge", "practice", "isolated", "mukta"],
  ["woman", "single", "leg", "bridge", "practice", "bosu", "ball", "thrust", "extension", "raise", "isolated"],
  ["woman", "single", "leg", "db", "deadlift", "isolated", "mukta"],
  ["woman", "single", "leg", "butt", "bridge", "practice", "isolated"],
  ["woman", "single", "leg", "resistance", "ring", "deadlift", "resistance", "ring", "practice", "isolated", "mukta"],
  ["woman", "single", "leg", "squat", "kickback", "practice", "mukta"],
  ["woman", "single", "leg", "squat", "pistol", "squat", "practice", "isolated"],
  ["woman", "single", "leg", "squat", "pistol", "squat", "isolated"],
  ["woman", "single", "leg", "squat", "pistol", "squat"],
  ["woman", "single", "one", "arm", "forward", "water", "bottle", "raise", "practice"],
  ["woman", "single", "one", "leg", "hop", "hop", "practice", "hop", "jumping", "practice"],
  ["woman", "single", "one", "leg", "hop", "hop", "practice"],
  ["woman", "sit", "up", "practice", "isolated", "mukta"],
  ["woman", "skater", "practice", "isolated", "mukta"],
  ["woman", "sled", "pushed", "practice", "isolated"],
  ["woman", "snap", "hop", "practice"],
  ["woman", "sphinx", "stand", "bound", "angel", "leg", "wall", "salamba", "bhujangasana", "pada", "baddha", "konasana", "wall"],
  ["woman", "spider", "man", "push", "up", "practice", "isolated", "mukta"],
  ["woman", "spiderman", "plank", "practice", "isolated", "mukta"],
  ["woman", "spinal", "column", "stand", "upward", "sitting", "straddle", "stand", "balancing", "bear", "stand", "merudandasana"],
  ["woman", "split", "alternating", "squat", "hop", "practice"],
  ["woman", "split", "squat", "curl", "practice", "mukta"],
  ["woman", "split", "squat", "practice", "mukta"],
  ["woman", "sprinter", "crunch", "practice", "isolated", "mukta"],
  ["woman", "squat", "jack", "practice", "mukta"],
  ["woman", "squat", "jack", "lat", "sumo", "walk", "practice"],
  ["woman", "squat", "hop", "ii", "step", "lat", "four", "strengthen", "entire", "lower", "body", "isolated"],
  ["woman", "squat", "lat", "kick", "practice", "isolated"],
  ["woman", "squat", "push", "practice", "isolated", "mukta"],
  ["woman", "balance", "swiss", "ball", "hamstring", "leg", "curl", "hip", "raise", "bridge"],
  ["woman", "balance", "swiss", "ball", "rollout", "practice", "woman", "workout", "fitness"],
  ["woman", "balance", "swiss", "ball", "push", "up", "practice", "isolated", "mukta"],
  ["woman", "balance", "swiss", "practice", "ball", "crunch", "practice", "isolated"],
  ["woman", "staff", "hand", "big", "toe", "stand", "ii", "practice", "padangustha", "dandasana", "ii", "isolated"],
  ["woman", "standing", "calf", "raise", "kettlebell", "practice"],
  ["woman", "standing", "crucifix", "body", "arm", "shoulder", "stretch", "practice"],
  ["woman", "standing", "crucifix", "chest", "curl", "practice", "isolated", "mukta"],
  ["woman", "standing", "kettlebell", "lat", "bend", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "standing", "elbow", "knee", "practice"],
  ["woman", "standing", "forward", "shoulder", "plate", "raise", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "standing", "hamstring", "stretch", "practice"],
  ["woman", "standing", "knee", "hug", "practice"],
  ["woman", "standing", "mountain", "climber", "practice", "isolated", "mukta"],
  ["woman", "standing", "open", "gate", "dynamic", "stretch", "gate", "opener", "practice", "mukta"],
  ["woman", "standing", "stand", "heavenly", "spirit", "stiti", "valakhilyasana", "yoga", "practice"],
  ["woman", "standing", "quad", "stretch", "practice", "mukta"],
  ["woman", "standing", "split", "stand", "urdhva", "prasarita", "era", "padasana", "practice", "isolated", "mukta"],
  ["woman", "standing", "split", "stand", "variation", "art", "wall", "hanumanasana", "variation", "art", "wall", "yoga", "practice"],
  ["woman", "star", "toe", "tap", "sit", "up", "practice", "isolated", "mukta"],
  ["woman", "stationary", "lunge", "bicep", "curl", "practice", "isolated"],
  ["woman", "step", "up", "crossover", "practice", "mukta"],
  ["woman", "step", "up", "knee", "raise", "practice", "isolated", "mukta"],
  ["woman", "step", "up", "knee", "raise", "practice", "isolated"],
  ["woman", "straddle", "raise", "stand", "hasta", "upavistha", "konasana", "yoga", "practice"],
  ["woman", "straight", "arm", "rope", "lat", "pulldown", "practice"],
  ["woman", "stutter", "step", "practice", "isolated", "mukta"],
  ["woman", "sumo", "kettlebell", "deadlift", "practice", "isolated", "mukta"],
  ["woman", "superman", "twist", "practice", "isolated"],
  ["woman", "supine", "spinal", "twist", "stand", "ii", "supta", "twist", "abdominal", "twist", "jathara", "parivartanasana"],
  ["woman", "supine", "split", "stand", "supta", "trivikramasana", "yoga", "practice"],
  ["woman", "salamba", "shoulderstand", "stand", "chair", "salamba", "shoulderstand", "stand", "chair", "yoga", "practice"],
  ["woman", "surrender", "practice", "isolated", "mukta"],
  ["woman", "swiss", "ball", "leg", "lift", "practice", "body", "kettlebell", "lift", "mukta"],
  ["woman", "swiss", "ball", "plank", "abdominal", "practice", "isolated", "mukta"],
  ["woman", "table", "overhead", "stand", "bharmanasana", "yoga", "practice"],
  ["woman", "mountain", "climber", "practice", "isolated"],
  ["woman", "suitcase", "sit", "up", "practice"],
  ["woman", "thread", "needle", "stand", "parsva", "balasana", "urdhva", "mukha", "pasasana", "yoga", "practice"],
  ["woman", "tri", "legged", "adho", "facing", "puppy", "stand", "variation", "tri", "pada", "adho", "mukha", "svanasana", "variation", "stacked"],
  ["woman", "tip", "toe", "squat", "practice"],
  ["woman", "toe", "tap", "practice"],
  ["woman", "toe", "squat", "stand", "ankle", "stretch", "stand", "isolated"],
  ["woman", "tap", "hop", "practice", "mukta"],
  ["woman", "trice", "dip", "practice"],
  ["woman", "tricep", "stretch", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "tricep", "stretch", "practice", "isolated", "mukta"],
  ["woman", "tripod", "headstand", "stand", "wide", "leg", "sirsasana", "ii", "konasana"],
  ["woman", "tripod", "headstand", "prep", "one", "knee", "elbow", "catur", "svanasana", "sirsasana", "eka", "janu", "kurpara"],
  ["woman", "tripod", "headstand", "prep", "one", "leg", "ardha", "raised", "catur", "svanasana", "sirsasana", "eka", "janu", "kurpara", "eka", "pada", "ardha", "urdhva"],
  ["woman", "trx", "pistol", "single", "leg", "squat", "long", "arm", "practice", "isolated"],
  ["woman", "trx", "stretch", "up", "practice", "isolated"],
  ["woman", "trx", "suspension", "strap", "suspended", "lunge", "practice", "isolated"],
  ["woman", "trx", "suspension", "strap", "tricep", "extension", "isolated"],
  ["woman", "twisted", "one", "legged", "arm", "handstand", "stand", "ii", "flying", "split", "stand", "hurdler", "stand", "eka", "pada", "koundinyasana", "ii"],
  ["woman", "twisted", "stand", "beautiful", "girl", "practice", "vakrasana", "isolated"],
  ["woman", "two", "arm", "kettlebell", "forward", "shoulder", "raise", "practice", "isolated", "mukta"],
  ["woman", "two", "arm", "kettlebell", "swing", "practice", "isolated"],
  ["woman", "niralamba", "bound", "one", "foot", "intense", "stretch", "stand", "niralamba", "baddha", "eka", "pada", "uttanasana"],
  ["woman", "niralamba", "shoulder", "stand", "stand", "yoga", "practice"],
  ["woman", "niralamba", "shoulder", "stand", "stand", "yoga", "practice"],
  ["woman", "niralamba", "shoulderstand", "stand", "variation", "prep", "niralamba", "shoulderstand", "variation", "prep"],
  ["woman", "up", "down", "plank", "practice", "isolated", "mukta"],
  ["woman", "overhead", "back", "opposite", "flye", "long", "resistance", "ring", "practice", "isolated"],
  ["woman", "standing", "kettlebell", "row", "practice"],
  ["woman", "sit", "curl", "press", "practice", "isolated", "mukta"],
  ["woman", "volcano", "stand", "upward", "hand", "stand", "upward", "salute", "stand", "tadasana", "urdhva", "hastasana"],
  ["woman", "waist", "trimmer", "practice"],
  ["woman", "wall", "bridge", "practice", "isolated", "mukta"],
  ["woman", "wall", "sit", "practice", "mukta"],
  ["woman", "weighted", "russian", "mason", "twist", "practice", "isolated", "workout", "character", "setu"],
  ["woman", "wheel", "stand", "chakrasana", "upward", "bow", "stand", "urdhva", "dhanurasana"],
  ["woman", "wheel", "stand", "flow", "chakrasana", "flow", "yoga", "practice"],
  ["woman", "wide", "squat", "calf", "raise", "practice"],
  ["woman", "wide", "stand", "sumo", "squat", "practice", "isolated"],
  ["woman", "yoga", "cat", "cow", "stretch", "practice", "mukta"],
  ["woman", "yoga", "setu", "bandha", "shoulderstand", "chakrasana", "yoga", "stand", "bridge", "physical", "fitness", "mukta"],
  ["woman", "high", "knee", "forward", "knee", "lift", "run", "jog", "stance", "practice", "isolated"],
  ["woman", "jumping", "jack"],
  ["woman", "practicing", "yoga", "arm", "stand", "astavakrasana", "asymmetrical", "arm", "handstand", "eight", "angel", "stand", "isolated"],
  ["woman", "scarecrow", "arm", "elbow", "shoulder", "rotation", "kettlebell"],
  ["woman", "stretching", "stand", "four", "ach", "treatment", "art", "shoulder", "arm", "neck", "back", "isolated"],
  ["woman", "strength", "abdominal", "ab", "prone", "single", "one", "leg", "lift", "raise", "isolated"],
  ["woman", "bosu", "ball", "bridge", "hip", "raise", "butt", "bridge"],
  ["woman", "burpee"],
  ["yoga", "man", "virabhadrasana", "ii", "soldier", "ii", "stand", "man", "cartoon", "character", "practicing", "hatha", "yoga", "man", "demonstrating", "practice", "during", "gymnastic", "training"],
  ["young", "man", "practice", "ab", "muscle", "press", "machine", "man", "ab", "crunch", "machine"],
  ["young", "pregnant", "woman", "sportswear", "doe", "sport", "practice", "transparent", "fitball", "training", "floor"],
  ["young", "woman", "practice", "ab", "muscle", "press", "machine", "woman", "ab", "crunch", "machine"]
]
  ,
  "glossary": [
    "ab", "air", "athlete", "background", "back", "bridge", "burpee", "butt", 
    "child", "dip", "doing", "dynamic", "exercise", "flat", "french", "guide", 
    "kick", "leg", "pose", "push", "raise", "squat", "stretch", "up", "woman", 
    "boxing", "boxer", "half", "handstand", "wall", "side", "variation", 
    "practice", "kapinjalasana", "vasisthasana", "hand", "toe", "knee", "bent", 
    "high", "illustrated", "healthy", "man", "lunge", "firming", "buttock", 
    "barbell", "bench", "jumping", "jack", "jump", "layered", "character", 
    "swing", "arm", "circle", "bodyweight", "cable", "chest", "free", "degree", 
    "turning", "rotation", "abdominal", "introduction", "elbow", "top", "front", 
    "view", "hiit", "accomplished", "siddhasana", "yoga", "active", "hamstring", 
    "alternating", "dumbbell", "curl", "different", "layer", "low", "trendy", 
    "style", "ankle", "roll", "arnold", "press", "assisted", "machine", 
    "seated", "tricep", "banana", "bananasana", "banded", "reverse", "lateral", 
    "fly", "row", "clean", "box", "block", "deadlift", "hack", "stepping", 
    "plate", "pullover", "wrist", "forearm", "romanian", "shrug", "windshield", 
    "wiper", "battle", "rope", "bear", "crawl", "standing", "bellow", "breath", 
    "bhastrika", "pranayama", "flye", "day", "bar", "hop", "exersice", "pike", 
    "swiss", "practicing", "med", "ball", "russian", "twist", "medicine", 
    "minimalistic", "floor", "single", "body", "upper", "bird", "dog", "reach", 
    "kickback", "posture", "six", "pack", "crunch", "cross", "tutorial", 
    "military", "overhead", "shoulder", "bosu", "hip", "mountain", "climber", 
    "walking", "down", "static", "balance", "bound", "angle", "baddha", 
    "konasana", "lotus", "padmasana", "hold", "setu", "bandha", "sarvangasana", 
    "bulgarian", "split", "set", "butterfly", "pec", "deck", "extension", 
    "core", "curling", "treadmill", "kettlebell", "dead", "bell", "bicycle", 
    "tri", "triangle", "skull", "pigeon", "twine", "picking", "german", "sit", 
    "diamond", "fold", "forward", "padangusthasana", "plough", "halasana", 
    "bhujangasana", "cobra", "viparita", "karani", "wind", "liberation", 
    "gas", "mukta", "jathara", "parivrtti", "supta", "sucirandhrasana", 
    "bhujang", "asana", "jalandhara", "octopus", "opposite", "advanced", "boat", 
    "naukasana", "seal", "elevated", "joint", "safe", "strength", "ring", 
    "scissor", "thrust", "bicep", "control", "cool", "cooldown", "pull", 
    "heel", "white", "vector", "superman", "weight", "raised", "laghu", 
    "prone", "isometric", "pulling", "pregnant", "beautiful", "old", "twisted", 
    "stable", "flow", "tuck", "straight", "throughout", "pointed", "stationary", 
    "chop", "lifting", "smash", "namaskar", "isolated", "dandasana", "quick", 
    "dancer", "anjaneyasana", "resistance", "quadricep", "doign", "slam", 
    "unsupported", "asymmetrical", "diagram", "close", "valakhilyasana", "tap", 
    "soldier", "plank", "step", "inchworm", "apanasana", "long", "grappling", 
    "stand", "master", "flamingo", "bag", "ardha", "grup", "shoulderstand", 
    "fetus", "tripod", "transparent", "equestrian", "foam", "office", "lat", 
    "rooster", "rolling", "doe", "position", "niralamba", "through", "double", 
    "kapotasana", "boy", "grip", "neck", "alanasa", "flute", "behind", 
    "trivikramasana", "pole", "adho", "gate", "surrender", "mukha", "fallen", 
    "paripurna", "stiti", "editable", "sunken", "muscle", "jerk", "folded", 
    "staff", "sport", "lifestyle", "file", "skier", "legged", "alanasan", 
    "preacher", "sitting", "good", "lolasana", "hug", "breakdancer", "cossack", 
    "sphinx", "trice", "upperbody", "four", "hatha", "keep", "icon", "angel", 
    "figure", "hex", "five", "punching", "hinge", "skater", "baby", "oblique", 
    "working", "spiderman", "matsyendrasana", "partial", "ustrasana", "band", 
    "gironda", "spider", "prasarita", "saw", "pumping", "inside", "stance", 
    "head", "cage", "physical", "spinal", "panna", "during", "garbhasana", 
    "garudasana", "headstand", "salamba", "downward", "strap", "abduction", 
    "ii", "hundred", "puppy", "morning", "self", "crucifix", "swelling", 
    "guidance", "renegade", "parallel", "against", "pistol", "era", 
    "illustration", "krounchasana", "abductor", "eagle", "start", "in", 
    "place", "bending", "bakasana", "chakrasana", "delt", "snake", "heavenly", 
    "crossover", "eye", "embryo", "sumo", "health", "padangustha", "art", 
    "phalakasana", "excellent", "wonderful", "magnificent", "fabulous", 
    "splendid", "marvelous", "remarkable", "incredible", "awesome", 
    "breathtaking", "exceptional", "brilliant", "admirable", "astonishing", 
    "unbelievable", "impressive", "fantastic", "splendiferous", "glorious", 
    "majestic", "workout", "fitness", "loss", "martial", "punch", "gym", 
    "training", "small", "glute", "face", "hammer", "pushdown", "cat", "tail", 
    "chair", "turn", "left", "right", "activity", "chin", "bodybuilding", 
    "pulldown", "horse", "cow", "gomukhasana", "crab", "touch", "crow", "bug", 
    "decline", "dipping", "laterally", "until", "horizontal", "supported", 
    "concentration", "hang", "snatch", "weighted", "wood", "pindasana", 
    "ashwa", "sanchalanasana", "water", "bottle", "using", "thigh", 
    "equipment", "calf", "explosive", "external", "needle", "ez", "fast", 
    "foot", "run", "crusher", "roller", "release", "frog", "incline", "full", 
    "functional", "ham", "developer", "gymnastic", "elastic", "hanging", "lift", 
    "jog", "spot", "bend", "twisting", "inverted", "jefferson", "skipping", 
    "cardio", "star", "nw", "plyo", "kettle", "goblet", "rowing", "swimmer", 
    "kneeling", "flexor"
  ]
}

###
GET {{host}}/models
Content-Type: application/json

###
POST {{host}}/train_model
Content-Type: application/json

{
  "name": "model1",
  "training_data": [
    [
      [ "woman", "step", "up", "knee", "raise" ],
      [
        "woman", "step", "up", "knee", "raise", "practice", "isolated"
      ]
    ],
    [
      [ "man", "jumping", "jack", "star" ],
      [ "man", "jumping", "jack", "star" ]
    ],
    [ [ "man", "arm", "ring" ], [ "man", "arm", "ring" ] ],
    [ [ "man", "bodyweight", "squat" ], [ "man", "bodyweight", "squat" ] ],
    [
      [ "man", "high", "knee" ],
      [
        "man",      "high",
        "knee",     "wall",
        "against",  "wall",
        "practice"
      ]
    ],
    [
      [ "man", "burpee" ],
      [ "man", "chest", "floor", "burpee", "practice", "isolated" ]
    ],
    [
      [ "man", "mountain", "climber" ],
      [ "man", "mountain", "climber", "practice", "isolated" ]
    ],
    [ [ "man", "not", "found" ], [ "not", "found" ] ],
    [
      [ "man", "hop", "squat" ],
      [ "man", "hop", "squat", "practice", "isolated" ]
    ],
    [ [ "man", "push", "up", "rotation" ], [ "push", "up", "rotation" ] ],
    [
      [ "man", "russian", "twist", "kettlebell" ],
      [ "russian", "twist", "kettlebell" ]
    ],
    [ [ "man", "jumping", "lunge" ], [ "jumping", "lunge" ] ],
    [
      [ "man", "hamstring", "stretch" ],
      [ "man", "hamstring", "stretch", "elastic", "ring", "practice" ]
    ],
    [
      [ "man", "shoulder", "stretch" ],
      [ "man", "opposite", "shoulder", "stretch", "practice", "isolated" ]
    ],
    [
      [ "man", "child", "stand" ],
      [ "man", "child", "stand", "stretch", "practice", "mukta" ]
    ],
    [
      [ "man", "burpee" ],
      [ "man", "chest", "floor", "burpee", "practice", "isolated" ]
    ],
    [
      [ "man", "mountain", "climber" ],
      [ "man", "mountain", "climber", "practice", "isolated" ]
    ],
    [ 
      [ "man", "not", "found" ], 
      [ "not", "found" ] 
    ],
    [
      [ "man", "hop", "squat" ],
      [ "man", "hop", "squat", "practice", "isolated" ]
    ],
    [ [ "man", "push", "up", "rotation" ], [ "push", "up", "rotation" ] ],
    [
      [ "man", "russian", "twist", "kettlebell" ],
      [ "russian", "twist", "kettlebell" ]
    ],
    [ [ "man", "jumping", "lunge" ], [ "jumping", "lunge" ] ],
    [
      [ "man", "burpee" ],
      [ "man", "chest", "floor", "burpee", "practice", "isolated" ]
    ],
    [
      [ "man", "mountain", "climber" ],
      [ "man", "mountain", "climber", "practice", "isolated" ]
    ],
    [ [ "man", "not", "found" ], [ "not", "found" ] ],
    [
      [ "man", "hop", "squat" ],
      [ "man", "hop", "squat", "practice", "isolated" ]
    ],
    [ [ "man", "push", "up", "rotation" ], [ "push", "up", "rotation" ] ],
    [
      [ "man", "russian", "twist", "kettlebell" ],
      [ "russian", "twist", "kettlebell" ]
    ],
    [ [ "man", "jumping", "lunge" ], [ "jumping", "lunge" ] ],
    [
      [ "man", "burpee" ],
      [ "man", "chest", "floor", "burpee", "practice", "isolated" ]
    ],
    [
      [ "man", "mountain", "climber" ],
      [ "man", "mountain", "climber", "practice", "isolated" ]
    ],
    [ [ "man", "not", "found" ], [ "not", "found" ] ],
    [
      [ "man", "hop", "squat" ],
      [ "man", "hop", "squat", "practice", "isolated" ]
    ],
    [ [ "man", "push", "up", "rotation" ], [ "push", "up", "rotation" ] ],
    [ [ "man", "jumping", "lunge" ], [ "jumping", "lunge" ] ],
    [
      [ "man", "russian", "twist", "kettlebell" ],
      [ "russian", "twist", "kettlebell" ]
    ]
  ]
}

###
POST {{host}}/search
Content-Type: application/json

{
  "name": "model1",
  "vector": ["jump", "squat"]
}

###
GET {{host}}/version
Content-Type: application/json