###
POST {{host}}/create_model
Content-Type: application/json

{
  "name": "model1",
  "dictionary": [
    ["jump", "squat"],
    ["squat"],
    ["jump", "lunge"],
    ["half", "lunge", "dumbbell"]
  ],
  "glossary": ["jump", "squat", "burpee", "tricep", "bridge", "dip", "half", "dumbbell", "lunge"]
}

###
GET {{host}}/models
Content-Type: application/json

###
POST {{host}}/train_model
Content-Type: application/json

{
  "name": "model1",
  "training_data": [
    [ ["jump", "squat"], ["jump", "squat"] ],
    [ ["squat"], ["squat"] ],
    [ ["jump", "lunge"], ["jump", "lunge"] ],
    [ ["half", "lunge", "dumbbell"], ["half", "lunge", "dumbbell"] ]
  ]
}

###
POST {{host}}/search
Content-Type: application/json

{
  "name": "model1",
  "vector": ["jump", "squat"]
}

###
GET {{host}}/version
Content-Type: application/json