###
POST {{host}}/create_model
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_create.json

###
PATCH {{host}}/update_model
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_create.json


###
POST {{host}}/train_model
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_train.json

###
POST {{host}}/search
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "vector": ["sit", "up"]
}

###
POST {{host}}/prepare_cache
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "puppet-o3",
  "neural_network_type": "SIAMESE",
  "search_vectors": [
    ["sit", "up"],
    ["push", "up"]
  ]
}

### 
POST {{host}}/test
Authorization: Bearer {{token}}
Content-Type: application/json

< ./puppet-o3_test.json