###
POST {{host}}/create_model
Content-Type: application/json

{
  "name": "puppet-o2",
  "neural_network_type": "GRU"
}

###
POST {{host}}/train_model
Content-Type: application/json

< ./puppet-o2_train.json


###
POST {{host}}/search
Content-Type: application/json

{
  "name": "puppet-o2",
  "neural_network_type": "GRU",
  "vector": [
      "ticket",
      "créer",
      "suite",
      "échange",
      "mails",
      "lucile",
      "delbarre",
      "pouvoir",
      "rajouterr",
      "emma",
      "georges",
      "coffre",
      "citer",
      "objet",
      "<ENTREPRISE>",
      "lucile",
      "emma",
      "emma",
      "bien",
      "ajouté",
      "coffre",
      "<COMPANY>",
      "bonne",
      "matiné",
      "<NAME>",
      "<ENTREPRISE>"
    ]
}

###
POST {{host}}/test
Content-Type: application/json

< ./puppet-o2_test.json